### ISSUE TITLE
Over 54K lines of warning for partial build with Tycho 2.7.0

### ISSUE THREAD

**Issue by dhendriks** [eclipse/tycho#761] opened 2022-03-13 10:44 UTC
Eclipse ESCET has a Maven/Tycho build. We have a full build, that works fine. But we also have partial builds, that build for instance only the documentation. We use for instance `clean verify --projects releng/org.eclipse.escet.releng.target,releng/org.eclipse.escet.releng.dev.documentation --also-make` to run this.

With Tycho 3.7.0, this now produces a staggering 54707 lines of warnings! See this file:

[54k-warning-lines.txt](https://github.com/eclipse/tycho/files/8239357/54k-warning-lines.txt)

I see the following issues:
* The are very many (too many?) warnings.
* Looking at the end, the last few sections of warnings, it seems there are many many duplicates, that only differ in one line. E.g.
  ```
  [WARNING] Following dependencies were not found by the slicer (you can disregard this if it is intentional):
  Unable to satisfy dependency from org.eclipse.escet.setext.texteditorbase 0.5.0.qualifier to osgi.bundle; org.eclipse.core.commands 3.9.600.
  Unable to satisfy dependency from org.eclipse.escet.setext.texteditorbase 0.5.0.qualifier to osgi.bundle; org.eclipse.ui.workbench 3.117.0.
  
  [WARNING] Following dependencies were not found by the slicer (you can disregard this if it is intentional):
  Unable to satisfy dependency from org.eclipse.escet.setext.texteditorbase 0.5.0.qualifier to osgi.bundle; org.eclipse.ui.workbench 3.117.0.
  ```
* The message `Following dependencies were not found by the slicer (you can disregard this if it is intentional):` does not help me at all. I have no clue what a slicer is. I can therefore not determine whether I can disregard this, as I don't know whether it is 'intentional'. I assume it all has something to do with doing a partial build? I couldn't find any information online about a Tycho slicer that would help me determine what is going on, what a slicer is, why the slicer can't find dependencies, and how to determine whether that is intentional or not.
* There is absolutely no way to get rid of (disable) the warnings, if they are intentional. I checked the source code and the warnings are printed unconditionally. It would be good to have a configuration option to disable such warnings, if I determine what they are intentional as Tycho indicates. Otherwise, there is no way to run this build without warnings.

**Comment by laeubi** [comment] 2022-03-13 16:40
Duplicate of #728

**Closed** 2022-03-13 20:30 UTC

**Comment by reckart** [comment] 2022-05-06 09:03
> It would be good to have a configuration option to disable such warnings, if I determine what they are intentional as Tycho indicates.

I believe there is still no option as of Tycho 2.7.2 to disable these warnings after one has determined that they are ok, e.g. because the respective artifacts are pom-first artifacts which are added e.g. to an update site via `<dependencies>`?

**Comment by laeubi** [comment] 2022-05-06 09:05
You can't disable them because they are not shown any more.
The warnings shown when using pom-first artifacts are of different kind and intentional.

**Comment by reckart** [comment] 2022-05-06 09:13
Indeed. I had forgotten that I had downgraded to Tycho 2.7.0 due to #932. With Tycho 2.7.3-SNAPSHOT, these warnings are gone.
