### ISSUE TITLE
[Tycho SureFire 2.3.0] org.eclipse.swt.SWTError cannot be found by org.eclipse.ui.workbench on Mac aarch64

### ISSUE THREAD

**Issue by Phillipus** [eclipse/tycho#184] opened 2021-07-13 18:14 UTC
Sorry if this is the wrong place to report this.

I'm running some Eclipse unit tests on a Mac Mini M1 (aarch64) using Tycho Surefire 2.3.0 that is failing with the error:

`java.lang.ClassNotFoundException: org.eclipse.swt.SWTError cannot be found by org.eclipse.ui.workbench_3.122.200.v20210506-1640`

This is working fine on Windows, Linux and Mac x86 (Intel), it only happens when running on Mac aarch64.

Error log attached.

[error.log](https://github.com/eclipse/tycho/files/6811074/error.log)

**Comment by mickaelistria** [comment] 2021-07-13 21:18
Is the SWT macosx.aarch64 bundle available in your target-platform? Did you configure the environments in target-platform-configuration ( https://www.eclipse.org/tycho/sitedocs/target-platform-configuration/target-platform-configuration-mojo.html#environments ) to consider this architecture?

**Comment by Phillipus** [comment] 2021-07-13 21:27
> Is the SWT macosx.aarch64 bundle available in your target-platform?

Yes, it is.

Here's some relevant parts of the main `pom.xml`:

```
<repositories>
    <repository>
        <id>Eclipse repository</id>
        <layout>p2</layout>
        <url>https://download.eclipse.org/releases/2021-06</url>
    </repository>
</repositories>
```

```
<plugin>
    <groupId>org.eclipse.tycho</groupId>
    <artifactId>target-platform-configuration</artifactId>
    <version>${tycho-version}</version>
    <configuration>
        <environments>
            <environment>
                <os>win32</os>
                <ws>win32</ws>
                <arch>x86_64</arch>
            </environment>
            <environment>
                <os>linux</os>
                <ws>gtk</ws>
                <arch>x86_64</arch>
            </environment>
            <environment>
                <os>macosx</os>
                <ws>cocoa</ws>
                <arch>x86_64</arch>
            </environment>
            <environment>
                <os>macosx</os>
                <ws>cocoa</ws>
                <arch>aarch64</arch>
            </environment>
        </environments>
    </configuration>
</plugin>
```
Main pom:
[pom.xml.txt](https://github.com/eclipse/tycho/files/6812076/pom.xml.txt)

Tests pom:
[pom-tests.xml.txt](https://github.com/eclipse/tycho/files/6812082/pom-tests.xml.txt)

It's all working fine running on Eclipse and JDK x86_64, just a problem with aarch64.

**Comment by Phillipus** [comment] 2021-07-13 21:38
To make things a bit clearer:

- Maven 3.8.1
- Azul JDK 11 aarch64 installed as default JDK
- `mvn clean verify`

**Comment by Phillipus** [comment] 2021-07-14 03:54
I've created a test project that reproduces the problem.

Requirements:

- Apple Silicon Mac
- Eclipse IDE 4.20 for Arm64 (https://download.eclipse.org/eclipse/downloads/drops4/R-4.20-202106111600/)
- Eclipse Maven plug-in (m2e - Maven Integration for Eclipse)
- Azul Zulu JDK for macOS ARM64 (https://www.azul.com/downloads/?version=java-11-lts&os=macos&architecture=arm-64-bit&package=jdk) installed into any directory

To run:

1. Add the Azul Zulu JDK as an Installed JRE in Eclipse Preferences
1. In Eclipse IDE's Run Configurations add a new Maven Build Launch Configuration with Base Directory set to the example project, and Goals as "clean verify".
3. Set the Launch Configuration's JRE to the Azul Zulu JDK
4. Run

[Test Project.zip](https://github.com/eclipse/tycho/files/6813394/Test.Project.zip)

**Comment by laeubi** [comment] 2021-07-14 05:44
You might enable [showEclipseLog](https://www.eclipse.org/tycho/sitedocs/tycho-surefire-plugin/test-mojo.html#showEclipseLog) as a first step to see in more details whats going on, this often revels the root cause of the problem.

> Requirements:
>     * Apple Silicon Mac

Where can Tycho developers get one for testing? :-)

> To run:

I think there is a higher chance if this could be replicated on command-line (ideally on linux/win as well, this shouldn't matter). If it only happens from within eclipse m2e then it is probably a configuration and/or m2e issue.

**Comment by laeubi** [comment] 2021-07-14 05:48
```
<environment>
	<os>macosx</os>
	<ws>cocoa</ws>
	<arch>x86_64</arch>
	</environment>
<environment>
	<os>macosx</os>
	<ws>cocoa</ws>
	<arch>aarch64</arch>
</environment>
```

I see a chance here that tycho picks the wrong env as there are two ones probably matching... can you try to exchange the first with the second entry or comment out one of them?

**Comment by Phillipus** [comment] 2021-07-14 05:50
> I think there is a higher chance if this could be replicated on command-line (ideally on linux/win as well, this shouldn't matter). If it only happens from within eclipse m2e then it is probably a configuration and/or m2e issue.

It can be replicated on the command line. I added the option of using Eclipse and m2e so that you could install different JDKs, as m2e allows you to set different JDK targets. I'll edit the instructions to not do this.

**Comment by Phillipus** [comment] 2021-07-14 05:55
> can you try to exchange the first with the second entry or comment out one of them?

Tried both of those options, same error.

**Comment by Phillipus** [comment] 2021-07-14 06:05
> You might enable showEclipseLog as a first step to see in more details whats going on, this often revels the root cause of the problem.

Log attached...

[error-log.txt](https://github.com/eclipse/tycho/files/6813884/error-log.txt)

**Comment by laeubi** [comment] 2021-07-14 06:13
Can you please try to build with latest [tycho snapshot](https://github.com/eclipse/tycho/wiki#getting-tycho-snapshots)?

**Comment by Phillipus** [comment] 2021-07-14 06:28
> Can you please try to build with latest [tycho snapshot](https://github.com/eclipse/tycho/wiki#getting-tycho-snapshots)?

I tried with `2.4.0-SNAPSHOT` and, unfortunately, it didn't solve the problem. 😢

**Comment by cdietrich** [comment] 2021-07-14 06:46
same with 2.5.0-SNAPSHOT

**Comment by laeubi** [comment] 2021-07-14 07:05
@cdietrich thans for calrification as 2.5.0 does not include any major change I would have suspect that. But as 2.4.0 includes updates p2/jdt stuff there was a little chance.

Sad enough I don't have the required hardware to investigate this directly but from the logs its seems that the
`Require-Capability: eclipse.platform; filter:="(& (osgi.ws=cocoa) (osgi.os=macosx) (osgi.arch=aarch64) )`
is missing in this case, so maybe there was a change in 2021-06 that is not reflected in current tycho-surefire or there is a dependency missing that needs to be imported by the test-probe, e.g. I noticed that the test-probe does not import swt at all (so maybe there is something lost).

This might even be a bug of P2 (@mickaelistria  ?) that P2 ignores Require-Capability when resolving dependencies.

**Comment by laeubi** [comment] 2021-07-14 07:08
> I tried with `2.4.0-SNAPSHOT` and, unfortunately, it didn't solve the problem.

Can you enable [printBundles](https://github.com/eclipse/tycho/blob/ac30b1f483a2d7c8f8684c4d487a8f078ec4d66e/tycho-surefire/tycho-surefire-plugin/src/main/java/org/eclipse/tycho/surefire/AbstractTestMojo.java#L227) with the  `2.4.0-SNAPSHOT`? This should emit a lit of bundles included and might reveal whats missing here...

**Comment by cdietrich** [comment] 2021-07-14 07:26
```
====== Installed Bundles ========
[0][32] org.eclipse.osgi (3.16.300.v20210525-1715)
[1][8] TestPlugin (1.0.0.qualifier)
[2][8] org.eclipse.ui (3.119.0.v20210111-1350)
[3][32] org.eclipse.core.runtime (3.22.0.v20210506-1025)
[4][32] org.eclipse.e4.ui.model.workbench (2.1.1000.v20210111-0958)
[5][4] org.junit (4.13.0.v20200204-1500)
[6][4] org.eclipse.osgi.util (3.6.0.v20210212-1137)
[7][4] org.eclipse.osgi.services (3.10.100.v20210324-0936)
[8][8] com.ibm.icu (67.1.0.v20200706-1749)
[9][8] com.sun.jna (5.8.0.v20210503-0343)
[10][4] com.sun.jna.platform (5.8.0.v20210406-1004)
[11][4] javax.annotation (1.3.5.v20200909-1856)
[12][4] org.apache.batik.constants (1.14.0.v20210324-0332)
[13][4] org.apache.xmlgraphics (2.6.0.v20210409-0748)
[14][4] org.w3c.dom.svg (1.1.0.v201011041433)
[15][4] org.w3c.css.sac (1.3.1.v200903091627)
[16][4] org.apache.batik.css (1.14.0.v20210324-0332)
[17][4] org.apache.batik.util (1.14.0.v20210324-0332)
[18][4] org.apache.batik.i18n (1.14.0.v20210324-0332)
[19][4] org.w3c.dom.events (3.0.0.draft20060413_v201105210656)
[20][4] org.apache.commons.io (2.8.0.v20210415-0900)
[21][4] org.apache.commons.logging (1.2.0.v20180409-1502)
[22][32] org.apache.felix.scr (2.1.24.v20200924-1939)
[23][8] org.eclipse.compare (3.8.0.v20210415-0713)
[24][8] org.eclipse.core.resources (3.15.0.v20210521-0722)
[25][4] org.eclipse.jface.text (3.18.0.v20210512-1640)
[26][8] org.eclipse.ui.ide (3.18.200.v20210523-1724)
[27][4] org.eclipse.ui.views (3.11.0.v20210111-1351)
[28][8] org.eclipse.ui.workbench.texteditor (3.16.100.v20210512-1009)
[29][8] org.eclipse.core.expressions (3.7.100.v20210203-1000)
[30][8] org.eclipse.ui.editors (3.14.100.v20210513-1110)
[31][4] org.eclipse.ui.forms (3.11.100.v20210108-1139)
[32][8] org.eclipse.compare.core (3.6.1000.v20201020-1107)
[33][4] org.eclipse.core.commands (3.10.0.v20210401-0744)
[34][32] org.eclipse.equinox.common (3.15.0.v20210518-0604)
[35][32] org.eclipse.core.contenttype (3.7.1000.v20210409-1722)
[36][32] org.eclipse.equinox.preferences (3.8.200.v20210212-1143)
[37][32] org.eclipse.equinox.registry (3.10.200.v20210503-1606)
[38][8] org.eclipse.core.databinding (1.10.100.v20200926-1123)
[39][4] org.eclipse.core.databinding.observable (1.10.0.v20200730-0848)
[40][8] org.eclipse.core.databinding.property (1.8.100.v20200619-0651)
[41][4] org.eclipse.core.filebuffers (3.7.0.v20210512-1543)
[42][4] org.eclipse.text (3.12.0.v20210512-1644)
[43][8] org.eclipse.core.filesystem (1.9.0.v20210419-1155)
[44][8] org.eclipse.core.jobs (3.11.0.v20210420-1453)
[45][8] org.eclipse.core.net (1.3.1100.v20210424-0724)
[46][8] org.eclipse.equinox.security (1.3.600.v20210126-1005)
[47][32] org.eclipse.equinox.app (1.5.100.v20210212-1143)
[48][4] org.eclipse.e4.core.commands (1.0.0.v20210507-1901)
[49][32] org.eclipse.e4.core.di (1.7.800.v20210526-1618)
[50][4] javax.inject (1.0.0.v20091030)
[51][32] org.eclipse.e4.core.contexts (1.8.400.v20191217-1710)
[52][8] org.eclipse.e4.core.services (2.2.600.v20210110-1654)
[53][4] org.eclipse.e4.core.di.annotations (1.6.600.v20191216-2352)
[54][8] org.eclipse.e4.core.di.extensions (0.16.0.v20200507-0938)
[55][32] org.eclipse.e4.core.di.extensions.supplier (0.16.0.v20210412-1358)
[56][4] org.eclipse.e4.emf.xpath (0.2.800.v20200609-0849)
[57][4] org.apache.commons.jxpath (1.3.0.v200911051830)
[58][32] org.eclipse.emf.ecore (2.24.0.v20210405-0628)
[59][8] org.eclipse.e4.ui.bindings (0.13.0.v20201119-1132)
[60][4] org.eclipse.swt (3.116.100.v20210602-2209)
[61][8] org.eclipse.e4.ui.services (1.5.0.v20210115-1333)
[62][4] org.eclipse.jface (3.22.200.v20210401-0958)
[63][4] org.eclipse.e4.ui.css.core (0.13.0.v20201015-0653)
[64][8] org.eclipse.e4.ui.css.swt (0.14.200.v20210401-1241)
[65][8] org.eclipse.e4.ui.css.swt.theme (0.13.0.v20201026-1147)
[66][32] org.eclipse.e4.ui.di (1.3.0.v20210222-1018)
[67][4] org.eclipse.e4.ui.dialogs (1.2.100.v20201109-2317)
[68][4] org.eclipse.e4.ui.ide (3.15.200.v20210108-1832)
[69][32] org.eclipse.equinox.event (1.6.0.v20210212-1143)
[70][4] org.eclipse.e4.ui.widgets (1.2.900.v20210412-0842)
[71][32] org.eclipse.e4.ui.workbench (1.13.0.v20210521-0741)
[72][8] org.eclipse.emf.ecore.change (2.14.0.v20190528-0725)
[73][8] org.eclipse.emf.ecore.xmi (2.16.0.v20190528-0725)
[74][8] org.eclipse.e4.ui.workbench.addons.swt (1.4.200.v20210321-1910)
[75][8] org.eclipse.e4.ui.workbench.renderers.swt (0.15.100.v20210515-1815)
[76][8] org.eclipse.e4.ui.workbench.swt (0.16.100.v20210315-1604)
[77][4] org.eclipse.jface.databinding (1.12.200.v20210111-0911)
[78][4] org.eclipse.e4.ui.workbench3 (0.15.500.v20201021-1339)
[79][4] org.eclipse.urischeme (1.1.400.v20210407-1558)
[80][32] org.eclipse.emf.common (2.22.0.v20210319-0732)
[81][8] org.eclipse.equinox.bidi (1.3.100.v20210212-1143)
[82][4] org.eclipse.equinox.launcher (1.6.200.v20210416-2027)
[83][8] org.eclipse.equinox.p2.core (2.7.0.v20210315-2042)
[84][8] org.eclipse.equinox.p2.engine (2.7.0.v20210328-0514)
[85][8] org.eclipse.equinox.p2.metadata (2.6.0.v20210331-1610)
[86][8] org.eclipse.equinox.p2.metadata.repository (1.4.0.v20210315-2228)
[87][8] org.eclipse.equinox.p2.repository (2.5.100.v20210329-1206)
[88][4] org.tukaani.xz (1.8.0.v20180207-1613)
[89][8] org.eclipse.help (3.9.0.v20210507-0822)
[90][4] org.eclipse.jface.notifications (0.3.0.v20210218-1820)
[91][8] org.eclipse.ltk.core.refactoring (3.11.400.v20210427-0555)
[92][8] org.eclipse.ltk.ui.refactoring (3.11.400.v20210320-1132)
[93][8] org.eclipse.ui.navigator (3.10.100.v20210415-0924)
[94][8] org.eclipse.team.core (3.9.0.v20210510-1748)
[95][8] org.eclipse.team.ui (3.9.0.v20210426-0837)
[96][2] org.eclipse.swt.win32.win32.x86_64 (3.116.100.v20210602-2209)
[97][8] org.eclipse.ui.workbench (3.122.200.v20210506-1640)
[98][8] org.eclipse.ui.ide.application (1.4.100.v20210506-1050)
[99][8] org.eclipse.ui.navigator.resources (3.8.100.v20210319-0848)
[100][4] org.eclipse.ui.views.properties.tabbed (3.9.100.v20201223-1348)
[101][4] org.hamcrest.core (1.3.0.v20180420-1519)
[102][4] org.w3c.dom.smil (1.0.1.v200903091627)
[103][2] org.eclipse.swt.gtk.linux.x86_64 (3.116.100.v20210602-2209)
[104][2] org.eclipse.swt.cocoa.macosx.x86_64 (3.116.100.v20210602-2209)
[105][2] org.eclipse.swt.cocoa.macosx.aarch64 (3.116.100.v20210602-2209)
[106][32] org.eclipse.tycho.surefire.osgibooter (2.5.0.202107092248)
[107][4] org.eclipse.tycho.surefire.junit4 (2.5.0.202107092249)
```

**Comment by cdietrich** [comment] 2021-07-14 07:26
interestingly org.eclipse.swt.cocoa.macosx.aarch64 (3.116.100.v20210602-2209) is there

**Comment by akurtakov** [comment] 2021-07-14 07:29
@cdietrich My commit has the potential to fix the issue but I don't have the way to test it either. I'll comment here when it's in latest tycho 2.5.0-SNAPSHOT.

**Comment by laeubi** [comment] 2021-07-14 07:30
Yeah and also all other fragments, that's a bit stupid but as tycho has worked before afaik.
```
[96][2] org.eclipse.swt.win32.win32.x86_64 (3.116.100.v20210602-2209)
[103][2] org.eclipse.swt.gtk.linux.x86_64 (3.116.100.v20210602-2209)
[104][2] org.eclipse.swt.cocoa.macosx.x86_64 (3.116.100.v20210602-2209)
[105][2] org.eclipse.swt.cocoa.macosx.aarch64 (3.116.100.v20210602-2209)
```

**Comment by Phillipus** [comment] 2021-07-14 07:31
Happy to test at any time.

**Comment by cdietrich** [comment] 2021-07-14 07:31
same here. (hope tycho can be built and installed locally)

**Comment by laeubi** [comment] 2021-07-14 07:36
I you can't await the new version:

- clone repository
- `mvn clean install -DskipTests`
- your all set with latest and greatest :-)

**Closed** 2021-07-14 08:34 UTC

**Comment by Phillipus** [comment] 2021-07-14 08:57
I cloned Tycho, ran `mvn clean install -DskipTests` and ran my test cases again...

**BUILD SUCCESS**

Thanks guys!

Can you tell me what is the best way to proceed for updating my `pom.xml`? Wait for next Tycho version? Why is there 2.4.0 and 2.5.0? Will this fix be in 2.4.0? Or just use 2.5.0-SNAPSHOT?

**Comment by cdietrich** [comment] 2021-07-14 08:57
same for me

**Comment by cdietrich** [comment] 2021-07-14 08:58
maybe we should start thinking of backporting some stuff to 2.4 and redo the staging.
or is 2.4 already out

**Comment by mickaelistria** [comment] 2021-07-14 09:03
> Will this fix be in 2.4.0?

No, because it's not a regression

> Or just use 2.5.0-SNAPSHOT?

Yes.

> maybe we should start thinking of backporting some stuff to 2.4 and redo the staging.

Some patches were already backported, but some regressions remain to be fixed before we can backport a fix and redo staging.

**Comment by laeubi** [comment] 2021-07-14 09:04
You can use [tycho snapshot](https://github.com/eclipse/tycho/wiki#getting-tycho-snapshots) in the meanwhile (the fix should appear there soon).

**Comment by laeubi** [comment] 2021-07-14 09:05
> No, because it's not a regression

I think it would be worth to backport this too, its easy to apply and a lots of people will start using the arm64 stuff now it is available.

**Comment by mickaelistria** [comment] 2021-07-19 15:32
Fix was backported to tycho-2.4.x branch and will be available in 2.4.0 release which should take place in the next days.

**Comment by Phillipus** [comment] 2021-07-19 15:34
> Fix was backported to tycho-2.4.x branch and will be available in 2.4.0 release which should take place in the next days.

Excellent! Thanks very much for that.

**Comment by mickaelistria** [comment] 2021-07-19 17:08
Please try https://oss.sonatype.org/content/repositories/orgeclipsetycho-1068 as new staging repo for 2.4 release, which should include the fix. I hope to release it tomorrow afternoon unless issue is not resolved or other blockers are found.

**Comment by Phillipus** [comment] 2021-07-19 17:33
> Please try https://oss.sonatype.org/content/repositories/orgeclipsetycho-1068 as new staging repo for 2.4 release, which should include the fix. I hope to release it tomorrow afternoon unless issue is not resolved or other blockers are found.

Confirmed as fixed.

```
<tycho-version>2.4.0</tycho-version>

<pluginRepositories>
    <pluginRepository>
        <id>tycho-snapshots</id>
        <url>https://oss.sonatype.org/content/repositories/orgeclipsetycho-1068/</url>
    </pluginRepository>
</pluginRepositories>
```
