### ISSUE TITLE
Junit5 @DisplayName and @ParameterizedTest name not shown on xml report 

### ISSUE THREAD

**Issue by gzunino** [eclipse/tycho#381] opened 2021-11-17 21:38 UTC
Since surefire-plugin 3.0.0-M4 it's possible to use junit 5 `@DisplayNames` and `@ParameterizedTest` `name` in surefire xml reports. 

See https://maven.apache.org/surefire/maven-surefire-plugin/examples/junit-platform.html#Surefire_Extensions_and_Reports_Configuration_for_.40DisplayName

For example, this test: https://github.com/junit-team/junit5-samples/blob/r5.7.1/junit5-jupiter-starter-maven/src/test/java/com/example/project/CalculatorTests.java

With maven-surefire 3.0.0-M5 configured as the link above, the surefire report xml file shows as:
```
  <testcase name="1 + 1 = 2" classname="com.example.project.CalculatorTests" time="0.016"/>
  <testcase name="0 + 1 = 1" classname="com.example.project.CalculatorTests" time="0.019"/>
  <testcase name="1 + 2 = 3" classname="com.example.project.CalculatorTests" time="0.001"/>
  <testcase name="49 + 51 = 100" classname="com.example.project.CalculatorTests" time="0.001"/>
  <testcase name="1 + 100 = 101" classname="com.example.project.CalculatorTests" time="0.001"/>
```
While the same test in tycho-surefire results in surefire xml report:
```
  <testcase name="addsTwoNumbers" classname="com.example.project.CalculatorTests" time="0.014"/>
  <testcase name="add{int, int, int}[1]" classname="com.example.project.CalculatorTests" time="0.014"/>
  <testcase name="add{int, int, int}[2]" classname="com.example.project.CalculatorTests" time="0.001"/>
  <testcase name="add{int, int, int}[3]" classname="com.example.project.CalculatorTests" time="0.001"/>
  <testcase name="add{int, int, int}[4]" classname="com.example.project.CalculatorTests" time="0"/>
```

This is specially bad for `ParameterizedTests`, because there is no way to distinguish test arguments. 
In Junit4 the parameterized argument values where shown in xml reports with tycho, and migrating to junit 5 that information is lost from the report.

The plugin configuration `<statelessTestsetReporter>` which enables display names in maven-surefire is ignored in tycho-surefire. I think tycho-surefire is using version 2.22 of maven-surefire, and will need to be updated to >=3.0.0-M4 to support this configuration.

**Comment by ernstblechaJKU** [comment] 2021-11-18 08:58
See also #198

**Comment by mickaelistria** [comment] 2021-11-18 09:29
Yes, actually a duplicate of #198 (which I retitled for clarification), let's close.

**Closed by mickaelistria** 2021-11-18 09:29 UTC

**Comment by laeubi** [comment] 2021-11-18 09:32
@mickaelistria [using the magic words](https://docs.github.com/en/issues/tracking-your-work-with-issues/marking-issues-or-pull-requests-as-a-duplicate) Duplicate of #198 will add a nice mark/reference to the issue....

**Comment by laeubi** [comment] 2021-11-18 09:33
Duplicate of #198
