### ISSUE TITLE
BaselineValidator.validateAndReplace() fails with UnsupportedOperationException under Maven 3.8.2

### ISSUE THREAD

**Issue by HannesWell** [eclipse/tycho#261] opened 2021-09-06 20:55 UTC
When using Maven 3.8.2 Tycho's `P2MetadataMojo` or `P2MetadataDefaultMojo` in version 2.4.0 (it is very likely the same for Tycho 2.5.0-SNAPSHOT because the class did not change) `BaselineValidator.validateAndReplace()` fails by throwing an `UnsupportedOperationException` when it attempts to remove an element from the list returned by `project.getAttachedArtifacts()` because the corresponding artifact is not present in the baseline.

As of Maven 3.8.2 `MavenProject.getAttachedArtifacts()` returns an unmodifiable List.
This was changed as part of the fix of [MNG-5868](https://issues.apache.org/jira/browse/MNG-5868) which was merged into the Maven master https://github.com/apache/maven/pull/358 and back-ported into the 3.8. stream as commit 66a43813770cd7dee9eb1ed0372e3f784ba0c541 (did not found the PR).

Unfortunately I did not found an alternative to remove attached artifacts from a MavenProjects.

**Comment by mickaelistria** [comment] 2021-09-06 21:16
Please ask about replacement on the Maven ticket, linking to this bug to point out that without good and backward compatible enough replacement, this can be interpreted as a serious functional regression from the API.

**Comment by laeubi** [comment] 2021-09-07 05:24
I think the problem is that the API never stated that one can modify the collection returned by `MavenProject.getAttachedArtifacts()`  Actually `MavenProject.addAttachedArtifact` states that `MavenProjectHelper` should be used that is described as:

> Convenience interface for plugins to add or replace artifacts and resources on projects.

so I think from the API of `MavenProjectHelper` that only add or replace is official supported but not removal and we are using undefined behavior here (and thus the result is also undefined).

As `MavenProject.setAttachedArtifacts(List<Artifact>)` is protected this seems to be the entry-point for the project-helper to support removal (if desired). The drawback of all of this would be that a plugin using this new API would require a specific maven version to work.

**Comment by laeubi** [comment] 2021-09-07 05:39
BTW I think one can bypass the restriction if only want replace instead of remove is desired by an Artifact with a specially-crafted-equals method that 

1. checks that the "other" artifact is also a bundle
2. considers two bundles equal if they match ignoring the classifier in the version

to replace (then this one will be removed from the list). Even though this sounds a bit bad, I think the whole implementation of "replace existing artifact" is badly designed in maven:

- If the artifact is already in the list (in the sense of equals), there is no need to add/replace it at all
- If (like the API states) it could happen that one needs to *update* e.g. the path for an artifact it is obviously **NOT** equal and should not be considered as such and one better updates the exiting artifact (e.g. change its path)
- Actually Artifact is an **interface(!)** and does not states anything about equality! It defines Comparable#compare but this is never used here! So instead of equals, `compare(...) == 0` would make more sense here.
- If one really likes to have this behavior there should be a (Linked)Map instead that has the specific properties of interest as its key instead of a List<...> (and then it would make perfectly sense to not allow modification of `MavenProject.getAttachedArtifacts()`)

**Comment by laeubi** [comment] 2021-09-07 05:42
> `BaselineValidator.validateAndReplace()` fails by throwing an `UnsupportedOperationException`

A first fix would be to catch UnsupportedOperationException (as it is perfectly valid from the collections framework API to throw one) and report this as error/warning/... instead with a useful user message.

**Comment by mickaelistria** [comment] 2021-09-07 08:34
The case of removing artifacts is arguable. If some artifact is not present in the baseline, I don't think it's particularly a reason to remove it; the new fresh build can totally still produce as artifact. One example would be baseline missing .pack.gz or -sources.jar but build producing them. In such case, an INFO note could probably be enough instead of trying to remove it.
WDYT

**Comment by HannesWell** [comment] 2021-09-07 22:43
> I think the problem is that the API never stated that one can modify the collection returned by `MavenProject.getAttachedArtifacts()` Actually `MavenProject.addAttachedArtifact` states that `MavenProjectHelper` should be used that is described as:
> 
> > Convenience interface for plugins to add or replace artifacts and resources on projects.
> 
> so I think from the API of `MavenProjectHelper` that only add or replace is official supported but not removal and we are using undefined behavior here (and thus the result is also undefined).
> 

One of my furst thoughts was also if Tycho uses unspecified behaviour here respectively I suspected that the returned list was never intended to support removal of attached artifacts.


> 
> 
> The case of removing artifacts is arguable. If some artifact is not present in the baseline, I don't think it's particularly a reason to remove it; the new fresh build can totally still produce as artifact. One example would be baseline missing .pack.gz or -sources.jar but build producing them. In such case, an INFO note could probably be enough instead of trying to remove it.
> WDYT

I have to admit that I'm not fully familiar with the `P2Metadata(Default)Mojo`, but looking at it from far away I would say it does not make sense to remove artifacts. Nevertheless replace unchanged artifacts with the baseline version to get binary equal builds sounds reasonable. Maybe some of the configuration options have to be re-worked/removed.


> 
> 
> Please ask about replacement on the Maven ticket, linking to this bug to point out that without good and backward compatible enough replacement, this can be interpreted as a serious functional regression from the API.

Do you still think I should report this upstream to Maven or should this be handled in Tycho?

**Comment by laeubi** [comment] 2021-09-08 07:03
> One example would be baseline missing .pack.gz or -sources.jar but build producing them. In such case, an INFO note could probably be enough instead of trying to remove it.

I think the goal here is to prevent that the pack or source jar contains different content, but maybe instead of remove the artifact it would be enough to set its file reference to null?

**Comment by mickaelistria** [comment] 2021-09-08 12:01
> I think the goal here is to prevent that the pack or source jar contains different content, but maybe instead of remove the artifact it would be enough to set its file reference to null?

Sounds good. Did you already try it?

**Comment by laeubi** [comment] 2021-09-08 12:28
I'm just poking around a bit in the maven source and at least not forbidden/enforced that a file is given for an artifact. So it might even be a backward compatible change in maven that an artifact updated with a null fill is removed from the list... But I don't know enough about this baseline-feature to guess if it might causes problems.

**Comment by HannesWell** [comment] 2021-09-09 07:15
Christoph or Mickael can you take care of this issue? I have to admit that I'm in favour for other things and I think you know better what has to be done here, than I do.

**Comment by akurtakov** [comment] 2021-09-21 18:01
This sounds important enough to delay 2.5.0 release for it.

**Comment by laeubi** [comment] 2021-09-22 04:16
> This sounds important enough to delay 2.5.0 release for it.

I'll try to propose a patch but think we should **not** delay the release anyways:

1. This only affects a specific maven version and is not a regression of tycho compared to a previous version, so if people are affected they can use and older maven version or skip this version.
2. it only affects a very specific feature of tycho-extras, so only people using that feature in a specific way need to be careful
3. if my patch is acceptable it will be fixed soon and we do not need to mind
4. if not it will take considerable time to fix this, maybe change maven, discuss different approaches, maybe there is no fix at all and we need to decide if we make a "tycho 3.0" and introduce a breaking change, in any way we can simply make another release as soon as this is addressed.

**Comment by laeubi** [comment] 2021-09-22 04:28
@HannesWell is there a simple reproducer/itest that shows the problem?

**Comment by HannesWell** [comment] 2021-09-22 06:16
> @HannesWell is there a simple reproducer/itest that shows the problem?

I encountered it reliably when building m2e with maven 3.8.2 using the usual command `mvn clean verify`.

As far as I know the affected goal is used often in Eclipse builds, which is why I suspect that other Eclipse projects could suffer the same issue (in case an artifact is removed there as well).

**Comment by HannesWell** [comment] 2021-09-22 06:22
Unfortunatly I cannot reproduce it at the moment because I cannot reach the [Download page of Maven](https://maven.apache.org/download.cgi).

I noticed this issue when Maven 3.8.2. was embedded into m2e. We noticed afterwards that there were additional test failures with that Maven version (have not yet investigated in detail why) and reverted the update. Nevertheless in the meantime I tried to build m2e from within the Eclipse IDE (with itself) and because I'm using the latested SNAPSHOT I noticed this issue.

**Comment by laeubi** [comment] 2021-09-22 06:34
You can use a mirror: https://downloads.apache.org/maven/maven-3/3.8.2/binaries/
I have build tycho +itests with maven 3.8.2 and got no test-failures so currently this case is not covered by itests.

**Comment by HannesWell** [comment] 2021-09-22 06:59
> 
> 
> You can use a mirror: https://downloads.apache.org/maven/maven-3/3.8.2/binaries/
> I have build tycho +itests with maven 3.8.2 and got no test-failures so currently this case is not covered by itests.

Thanks for the link.
When I build m2e locally with Maven 3.8.2 the build (mvn clean verify) fails for the Default Build Lifecycle Mapping Metadata Plug-in:
```
[INFO] -----< org.eclipse.m2e:org.eclipse.m2e.lifecyclemapping.defaults >------
[INFO] Building [bundle] Default Build Lifecycle Mapping Metadata 1.17.1-SNAPSHOT [13/41]
[INFO] ---------------------------[ eclipse-plugin ]---------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.4.1:clean (default-clean) @ org.eclipse.m2e.lifecyclemapping.defaults ---
[INFO]
[INFO] --- tycho-packaging-plugin:2.4.0:build-qualifier (default-build-qualifier) @ org.eclipse.m2e.lifecyclemapping.defaults ---
[INFO] The project's OSGi version is 1.17.1.20210115-1536
[INFO]
[INFO] --- tycho-packaging-plugin:2.4.0:validate-id (default-validate-id) @ org.eclipse.m2e.lifecyclemapping.defaults ---
[INFO]
[INFO] --- tycho-packaging-plugin:2.4.0:validate-version (default-validate-version) @ org.eclipse.m2e.lifecyclemapping.defaults ---
[INFO]
[INFO] --- target-platform-configuration:2.4.0:target-platform (default-target-platform) @ org.eclipse.m2e.lifecyclemapping.defaults ---
[INFO]
[INFO] --- jacoco-maven-plugin:0.8.5:prepare-agent (default) @ org.eclipse.m2e.lifecyclemapping.defaults ---
[INFO] argLine set to -javaagent:C:\\Users\\Hannes\\.m2\\repository\\org\\jacoco\\org.jacoco.agent\\0.8.5\\org.jacoco.agent-0.8.5-runtime.jar=destfile=C:\\dev\\git\\eclipse.m2e-core\\target\\jacoco.exec,append=true,includes=org.eclipse.m2e*:org.apache.maven*:org.eclipse.aether*
[INFO]
[INFO] --- maven-resources-plugin:2.5:resources (default-resources) @ org.eclipse.m2e.lifecyclemapping.defaults ---
[debug] execute contextualize
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\dev\git\eclipse.m2e-core\org.eclipse.m2e.lifecyclemapping.defaults\src\main\resources
[INFO]
[INFO] --- tycho-compiler-plugin:2.4.0:compile (default-compile) @ org.eclipse.m2e.lifecyclemapping.defaults ---
[INFO]
[INFO] --- maven-resources-plugin:2.5:testResources (default-testResources) @ org.eclipse.m2e.lifecyclemapping.defaults ---
[debug] execute contextualize
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\dev\git\eclipse.m2e-core\org.eclipse.m2e.lifecyclemapping.defaults\src\test\resources
[INFO]
[INFO] --- tycho-compiler-plugin:2.4.0:testCompile (default-testCompile) @ org.eclipse.m2e.lifecyclemapping.defaults ---
[INFO]
[INFO] --- maven-surefire-plugin:2.8:test (default-test) @ org.eclipse.m2e.lifecyclemapping.defaults ---
[INFO] No tests to run.
[INFO] Surefire report directory: C:\dev\git\eclipse.m2e-core\org.eclipse.m2e.lifecyclemapping.defaults\target\surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
There are no tests to run.

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

[INFO]
[INFO] --- tycho-source-plugin:2.4.0:plugin-source (plugin-source) @ org.eclipse.m2e.lifecyclemapping.defaults ---
[INFO] Building jar: C:\dev\git\eclipse.m2e-core\org.eclipse.m2e.lifecyclemapping.defaults\target\org.eclipse.m2e.lifecyclemapping.defaults-1.17.1-SNAPSHOT-sources.jar
[INFO]
[INFO] --- tycho-packaging-plugin:2.4.0:package-plugin (default-package-plugin) @ org.eclipse.m2e.lifecyclemapping.defaults ---
[INFO] Building jar: C:\dev\git\eclipse.m2e-core\org.eclipse.m2e.lifecyclemapping.defaults\target\org.eclipse.m2e.lifecyclemapping.defaults-1.17.1-SNAPSHOT.jar
[INFO]
[INFO] --- tycho-p2-plugin:2.4.0:p2-metadata-default (default-p2-metadata-default) @ org.eclipse.m2e.lifecyclemapping.defaults ---
[WARNING] MavenProject: org.eclipse.m2e:org.eclipse.m2e.lifecyclemapping.defaults:1.17.1-SNAPSHOT @ C:\dev\git\eclipse.m2e-core\org.eclipse.m2e.lifecyclemapping.defaults\.polyglot.META-INF: baseline and build artifacts have same version but different contents
   no-classifier: different
      META-INF/ECLIPSE_.RSA: present in baseline only
      META-INF/ECLIPSE_.SF: present in baseline only
      META-INF/MANIFEST.MF: different
         Bundle-License: not present in baseline version
      about.html: different
      lifecycle-mapping-metadata.xml: different
   classifier-sources: not present in baseline

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Maven Integration for Eclipse (parent) 1.16.0-SNAPSHOT SUCCESS [  0.249 s]
[INFO] [target] m2e-target-platform 1.16.0-SNAPSHOT ....... SUCCESS [  0.193 s]
[INFO] [bundle] Maven Project Model Edit Bundle 1.18.2-SNAPSHOT SUCCESS [ 22.695 s]
[INFO] Maven Integration for Eclipse Core Plug-in 1.18.2-SNAPSHOT SUCCESS [ 15.122 s]
[INFO] [bundle] Maven Integration for Eclipse 1.18.2-SNAPSHOT SUCCESS [ 11.787 s]
[INFO] [bundle] Maven Integration for Eclipse Launching 1.17.4-SNAPSHOT SUCCESS [  3.474 s]
[INFO] [bundle] Maven Integration for Eclipse JDT 1.18.2-SNAPSHOT SUCCESS [  5.206 s]
[INFO] [bundle] Maven Integration for Eclipse JDT UI 1.17.2-SNAPSHOT SUCCESS [  2.410 s]
[INFO] [bundle] Maven Integration for Eclipse Refactoring 1.17.3-SNAPSHOT SUCCESS [  5.093 s]
[INFO] [bundle] m2e Marketplace 1.18.1-SNAPSHOT ........... SUCCESS [  4.738 s]
[INFO] [bundle] Maven Integration for Eclipse (Editors) 1.18.2-SNAPSHOT SUCCESS [ 12.023 s]
[INFO] [bundle] Maven POM XML Editor 1.18.2-SNAPSHOT ...... SUCCESS [  4.875 s]
[INFO] [bundle] Default Build Lifecycle Mapping Metadata 1.17.1-SNAPSHOT FAILURE [  1.462 s]
[INFO] [bundle] SCM Maven Integration for Eclipse 1.17.2-SNAPSHOT SKIPPED
[INFO] [bundle] Maven Profiles Management 1.17.1-SNAPSHOT . SKIPPED
[INFO] [bundle] Maven Profiles Management UI 1.17.3-SNAPSHOT SKIPPED
[INFO] [bundle] m2e extension for import framework 1.17.3-SNAPSHOT SKIPPED
[INFO] [bundle] Source Lookup Core 1.17.4-SNAPSHOT ........ SKIPPED
[INFO] [bundle] Binary project Core 1.17.4-SNAPSHOT ....... SKIPPED
[INFO] [bundle] Binary project UI 1.18.1-SNAPSHOT ......... SKIPPED
[INFO] [bundle] Source Lookup UI 1.17.3-SNAPSHOT .......... SKIPPED
[INFO] org.eclipse.m2e.editor.lemminx 1.18.2-SNAPSHOT ..... SKIPPED
[INFO] [bundle] M2E PDE Integration 1.18.2-SNAPSHOT ....... SKIPPED
[INFO] [bundle] PDE Integration UI 1.18.2-SNAPSHOT ........ SKIPPED
[INFO] [bundle] M2E Testing Helpers 1.17.4-SNAPSHOT ....... SKIPPED
[INFO] [bundle] m2e logback appender 1.17.1-SNAPSHOT ...... SKIPPED
[INFO] [bundle] m2e logback configuration 1.16.3-SNAPSHOT . SKIPPED
[INFO] [feature] POM Editor (Legacy) using WebTools SourceEditing UI 1.18.2-SNAPSHOT SKIPPED
[INFO] [feature] m2e - Maven Integration for Eclipse (includes Incubating components) 1.18.2-SNAPSHOT SKIPPED
[INFO] [feature] POM Editor using LemMinX language server (includes Incubating components) 1.18.2-SNAPSHOT SKIPPED
[INFO] [feature] m2e - Extensions Development Support (Optional) 1.18.2-SNAPSHOT SKIPPED
[INFO] [feature] m2e - slf4j over logback logging (Optional) 1.17.2-SNAPSHOT SKIPPED
[INFO] [feature] m2e PDE - Maven Integration for Eclipse Plugin Development 1.18.2-SNAPSHOT SKIPPED
[INFO] Maven Integration for Eclipse Update Site 1.16.0-SNAPSHOT SKIPPED
[INFO] org.eclipse.m2e.core.tests 1.16.1-SNAPSHOT ......... SKIPPED
[INFO] org.eclipse.m2e.core.ui.tests 1.18.1-SNAPSHOT ...... SKIPPED
[INFO] Tests for Maven Integration for Eclipse Importer framework 1.16.1-SNAPSHOT SKIPPED
[INFO] [test-bundle] Bundle-Name 1.16.0-SNAPSHOT .......... SKIPPED
[INFO] [test-bundle] Test for pom edition in generic editor 1.16.0-SNAPSHOT SKIPPED
[INFO] [test-bundle] org.eclipse.m2e.jdt.tests 1.16.2-SNAPSHOT SKIPPED
[INFO] [test-bundle] Test for pom edition in WTP-based editor 1.16.0-SNAPSHOT SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  04:18 min
[INFO] Finished at: 2021-09-22T08:55:00+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-p2-plugin:2.4.0:p2-metadata-default (default-p2-metadata-default) on project org.eclipse.m2e.lifecyclemapping.defaults: Execution default-p2-metadata-default of goal org.eclipse.tycho:tycho-p2-plugin:2.4.0:p2-metadata-default failed.: UnsupportedOperationException -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :org.eclipse.m2e.lifecyclemapping.defaults
```

**Comment by laeubi** [comment] 2021-09-22 10:58
@HannesWell can you check if https://github.com/eclipse/tycho/pull/301 fixes the issue for you? If jes I think we should merge this for now (at least for 2.5.0 release ...)

**Comment by HannesWell** [comment] 2021-09-22 21:01
> 
> 
> @HannesWell can you check if #301 fixes the issue for you? If jes I think we should merge this for now (at least for 2.5.0 release ...)

Unfortunately not because the m2e build fails when using the current Tycho 2.5.0-SNAPSHOTs, even without your changes.
I created a draft PR demonstrate the failures: https://github.com/eclipse-m2e/m2e-core/pull/334.

**Closed** 2021-09-23 03:39 UTC

**Comment by akurtakov** [comment] 2021-09-23 05:52
Yesterday was a day off for both Mickael and me. Thanks for taking care of it.

**Comment by HannesWell** [comment] 2021-09-25 13:25
> 
> 
> @HannesWell can you check if #301 fixes the issue for you? If jes I think we should merge this for now (at least for 2.5.0 release ...)

Now that M2E builds with the Tycho-2.5.0-SNAPSHOT I run the build again using Maven 3.8.2 and can confirm that the build succeededs now.
Thank you @laeubi your fix solved this problem.

**Comment by laeubi** [comment] 2022-05-19 12:09
> Unfortunately I did not found an alternative to remove attached artifacts from a MavenProjects.

There is now a discussion in maven here: https://issues.apache.org/jira/browse/MNG-7316 please join the discussion and share insights so we can get a more official solution.
