### ISSUE TITLE
3.0: new resolver and com.googlecode.addjars.mojo.AddJarsMojo dont like each other

### ISSUE THREAD

**Issue by cdietrich** [eclipse/tycho#1159] opened 2022-07-19 06:28 UTC
this is a spin off from #1127

```
2022-07-12T05:00:43.6647688Z org.eclipse.tycho.core.osgitools.OsgiManifestParserException: Exception parsing OSGi MANIFEST /home/runner/work/xtext-reference-projects/xtext-reference-projects/domainmodel/2.28.0/org.eclipse.xtext.example.domainmodel.ide/target/com.googlecode.addjars.mojo.AddJarsMojo/META-INF/MANIFEST.MF: Manifest file not found
2022-07-12T05:00:43.6649343Z     at org.eclipse.tycho.core.osgitools.DefaultBundleReader.loadManifestFromDirectory (DefaultBundleReader.java:96)
2022-07-12T05:00:43.6650588Z     at org.eclipse.tycho.core.osgitools.DefaultBundleReader.doLoadManifest (DefaultBundleReader.java:63)
2022-07-12T05:00:43.6651547Z     at org.eclipse.tycho.core.osgitools.DefaultBundleReader.loadManifest (DefaultBundleReader.java:54)
2022-07-12T05:00:43.6652248Z     at org.eclipse.tycho.core.maven.MavenDependencyInjector.getClasspathElements (MavenDependencyInjector.java:209)
2022-07-12T05:00:43.6652992Z     at org.eclipse.tycho.core.maven.MavenDependencyInjector.collectProjectDependencies (MavenDependencyInjector.java:278)
2022-07-12T05:00:43.6653714Z     at org.eclipse.tycho.core.maven.MavenDependencyInjector.addDependency (MavenDependencyInjector.java:135)
2022-07-12T05:00:43.6654425Z     at org.eclipse.tycho.core.maven.MavenDependencyInjector.injectMavenDependencies (MavenDependencyInjector.java:68)
2022-07-12T05:00:43.6655195Z     at org.eclipse.tycho.p2.resolver.P2DependencyResolver.injectDependenciesIntoMavenModel (P2DependencyResolver.java:502)
2022-07-12T05:00:43.6655901Z     at org.eclipse.tycho.core.resolver.DefaultTychoResolver.resolveProject (DefaultTychoResolver.java:181)
2022-07-12T05:00:43.6656645Z     at org.eclipse.tycho.core.maven.TychoProjectExecutionListener.beforeProjectExecution (TychoProjectExecutionListener.java:47)
2022-07-12T05:00:43.6657624Z     at org.apache.maven.lifecycle.internal.CompoundProjectExecutionListener.beforeProjectExecution (CompoundProjectExecutionListener.java:43)
2022-07-12T05:00:43.6658464Z     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:106)
2022-07-12T05:00:43.6659152Z     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
2022-07-12T05:00:43.6659920Z     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
2022-07-12T05:00:43.6660633Z     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
2022-07-12T05:00:43.6661132Z     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:294)
2022-07-12T05:00:43.6661537Z     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
2022-07-12T05:00:43.6661949Z     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
2022-07-12T05:00:43.6662346Z     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)
2022-07-12T05:00:43.6662716Z     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
2022-07-12T05:00:43.6663087Z     at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
2022-07-12T05:00:43.6663515Z     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
2022-07-12T05:00:43.6664035Z     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
2022-07-12T05:00:43.6687966Z     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
2022-07-12T05:00:43.6701759Z     at java.lang.reflect.Method.invoke (Method.java:566)
2022-07-12T05:00:43.6702275Z     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
2022-07-12T05:00:43.6702848Z     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
2022-07-12T05:00:43.6703397Z     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launc
```

steps to reproduce

```
git clone https://github.com/itemis/xtext-reference-projects.git
cd xtext-reference-projects
export EXTRA_ARGS="-Dtycho-version=3.0.0-SNAPSHOT -Ptycho_snapshots -Dtycho.resolver.classic=false"
scripts/domainmodel-2.28.sh
```

integ test: https://github.com/eclipse/tycho/pull/1145

**Comment by laeubi** [comment] 2022-07-21 05:34
@cdietrich the problem is [here](https://github.com/kahing/addjars-maven-plugin/blob/df8464b532463036d6358935810360bac7c562ce/src/main/java/com/googlecode/addjars/mojo/AddJarsMojo.java#L122):
where the `AddJarsMojo` set the pom file to be in the target directory what in turn adjusts the base-dir.

For this specific case I might be able to adjust the code that it do not fails at this stage (as the project ref is already there, there is no need to update it here again) but actually the `AddJarsMojo` behaves bad here and should be fixed.

**Closed** 2022-07-21 16:17 UTC

**Comment by cdietrich** [comment] 2022-07-21 18:42
many thanks @laeubi
