### ISSUE TITLE
Error when fetching repository from maven zip artifact

### ISSUE THREAD

**Issue by ghillairet** [eclipse/tycho#271] opened 2021-09-15 11:50 UTC
I am using this feature introduced in tycho [2.2](https://wiki.eclipse.org/Tycho/Release_Notes/2.2#Support_for_consuming_maven_artifacts_made_of_zipped_P2_update_sites) but I am getting this exception when trying to load a repository, not sure if it is a problem with the repository or a bug in tycho.

Note that I can reproduce the issue with tycho 2.3, 2.4 and 2.5-SNAPSHOT, but I guess the issue could be in the p2 version.

```
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-packaging-plugin:2.5.0-SNAPSHOT:package-feature (default-package-feature) on project com.ataccama.ide.one.feature: Execution default-package-feature of goal org.eclipse.tycho:tycho-packaging-plugin:2.5.0-SNAPSHOT:package-feature failed: Load repository from url mvn:com.ataccama.extension.salesforce:com.ataccama.extension.salesforce.ide.repository:0.2.1-SNAPSHOT:zip failed (org.eclipse.equinox.p2.core.ProvisionException: No repository found at mvn:com.ataccama.extension.salesforce:com.ataccama.extension.salesforce.ide.repository:0.2.1-SNAPSHOT:zip.) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.eclipse.tycho:tycho-packaging-plugin:2.5.0-SNAPSHOT:package-feature (default-package-feature) on project com.ataccama.ide.one.feature: Execution default-package-feature of goal org.eclipse.tycho:tycho-packaging-plugin:2.5.0-SNAPSHOT:package-feature failed: Load repository from url mvn:com.ataccama.extension.salesforce:com.ataccama.extension.salesforce.ide.repository:0.2.1-SNAPSHOT:zip failed (org.eclipse.equinox.p2.core.ProvisionException: No repository found at mvn:com.ataccama.extension.salesforce:com.ataccama.extension.salesforce.ide.repository:0.2.1-SNAPSHOT:zip.)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:972)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-package-feature of goal org.eclipse.tycho:tycho-packaging-plugin:2.5.0-SNAPSHOT:package-feature failed: Load repository from url mvn:com.ataccama.extension.salesforce:com.ataccama.extension.salesforce.ide.repository:0.2.1-SNAPSHOT:zip failed (org.eclipse.equinox.p2.core.ProvisionException: No repository found at mvn:com.ataccama.extension.salesforce:com.ataccama.extension.salesforce.ide.repository:0.2.1-SNAPSHOT:zip.)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:148)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:972)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: java.lang.RuntimeException: Load repository from url mvn:com.ataccama.extension.salesforce:com.ataccama.extension.salesforce.ide.repository:0.2.1-SNAPSHOT:zip failed (org.eclipse.equinox.p2.core.ProvisionException: No repository found at mvn:com.ataccama.extension.salesforce:com.ataccama.extension.salesforce.ide.repository:0.2.1-SNAPSHOT:zip.)
    at org.eclipse.tycho.repository.p2base.artifact.repository.RepositoryArtifactProvider.loadRepository (RepositoryArtifactProvider.java:118)
    at org.eclipse.tycho.repository.p2base.artifact.repository.LazyArtifactRepository.getDelegate (LazyArtifactRepository.java:50)
    at org.eclipse.tycho.repository.p2base.artifact.repository.LazyArtifactRepository.contains (LazyArtifactRepository.java:87)
    at org.eclipse.tycho.repository.p2base.artifact.repository.RepositoryArtifactProvider.contains (RepositoryArtifactProvider.java:137)
    at org.eclipse.tycho.repository.local.MirroringArtifactProvider.contains (MirroringArtifactProvider.java:110)
    at org.eclipse.tycho.repository.p2base.artifact.provider.CompositeArtifactProvider.contains (CompositeArtifactProvider.java:59)
    at org.eclipse.tycho.repository.p2base.artifact.provider.CompositeArtifactProvider.getArtifactFile (CompositeArtifactProvider.java:86)
    at org.eclipse.tycho.p2.target.TargetPlatformBaseImpl.getArtifactLocation (TargetPlatformBaseImpl.java:142)
    at org.eclipse.tycho.p2.target.FinalTargetPlatformImpl.getArtifactLocation (FinalTargetPlatformImpl.java:1)
    at org.eclipse.tycho.packaging.FeatureXmlTransformer.expandReferences (FeatureXmlTransformer.java:65)
    at org.eclipse.tycho.packaging.PackageFeatureMojo.expandVersionQualifiers (PackageFeatureMojo.java:259)
    at org.eclipse.tycho.packaging.PackageFeatureMojo.execute (PackageFeatureMojo.java:126)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:972)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: org.eclipse.equinox.p2.core.ProvisionException: No repository found at mvn:com.ataccama.extension.salesforce:com.ataccama.extension.salesforce.ide.repository:0.2.1-SNAPSHOT:zip.
    at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.fail (AbstractRepositoryManager.java:397)
    at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository (AbstractRepositoryManager.java:701)
    at org.eclipse.equinox.internal.p2.artifact.repository.ArtifactRepositoryManager.loadRepository (ArtifactRepositoryManager.java:131)
    at org.eclipse.equinox.internal.p2.artifact.repository.ArtifactRepositoryManager.loadRepository (ArtifactRepositoryManager.java:125)
    at org.eclipse.tycho.p2.remote.RemoteArtifactRepositoryManager.loadRepository (RemoteArtifactRepositoryManager.java:105)
    at org.eclipse.tycho.repository.p2base.artifact.repository.RepositoryArtifactProvider.loadRepository (RepositoryArtifactProvider.java:116)
    at org.eclipse.tycho.repository.p2base.artifact.repository.LazyArtifactRepository.getDelegate (LazyArtifactRepository.java:50)
    at org.eclipse.tycho.repository.p2base.artifact.repository.LazyArtifactRepository.contains (LazyArtifactRepository.java:87)
    at org.eclipse.tycho.repository.p2base.artifact.repository.RepositoryArtifactProvider.contains (RepositoryArtifactProvider.java:137)
    at org.eclipse.tycho.repository.local.MirroringArtifactProvider.contains (MirroringArtifactProvider.java:110)
    at org.eclipse.tycho.repository.p2base.artifact.provider.CompositeArtifactProvider.contains (CompositeArtifactProvider.java:59)
    at org.eclipse.tycho.repository.p2base.artifact.provider.CompositeArtifactProvider.getArtifactFile (CompositeArtifactProvider.java:86)
    at org.eclipse.tycho.p2.target.TargetPlatformBaseImpl.getArtifactLocation (TargetPlatformBaseImpl.java:142)
    at org.eclipse.tycho.p2.target.FinalTargetPlatformImpl.getArtifactLocation (FinalTargetPlatformImpl.java:1)
    at org.eclipse.tycho.packaging.FeatureXmlTransformer.expandReferences (FeatureXmlTransformer.java:65)
    at org.eclipse.tycho.packaging.PackageFeatureMojo.expandVersionQualifiers (PackageFeatureMojo.java:259)
    at org.eclipse.tycho.packaging.PackageFeatureMojo.execute (PackageFeatureMojo.java:126)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:972)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
[ERROR]
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
```

**Comment by ghillairet** [comment] 2021-09-15 11:54
Just note that I can track down the issue to here https://git.eclipse.org/c/equinox/rt.equinox.p2.git/tree/bundles/org.eclipse.equinox.p2.repository/src/org/eclipse/equinox/internal/p2/repository/helpers/AbstractRepositoryManager.java?h=R4_20_maintenance#n185

```
RepositoryInfo<T> info = repositories.get(getKey(location));
if (info == null || info.repository == null)
   return null;
```

At this point info is always null.

**Comment by laeubi** [comment] 2021-09-15 11:56
Can you provide a public accessible example for this to investigate? I find it a bit strange that this happens while `tycho-packaging-plugin` execution (and not before).

As you are using a SNAPSHOT reference, is this isntalled in your local repository (or repro mananager) before you call tycho?

**Comment by laeubi** [comment] 2021-09-16 17:07
Can you download the artifact from maven and check if it contains an `artifacts.xml.xz`? Maybe this is the problem here.

**Comment by apeteri** [comment] 2021-09-17 08:42
This seems to be a duplicate of #30 . As a workaround, try adding a small bundle project (can be as simple as an activator class that does nothing) which depends on an artifact in the IDE repository via eg. a `Require-Bundle` directive. This pushes the metadata download step to the beginning of the build, where it still works as it is happening on the main thread.

**Comment by laeubi** [comment] 2021-09-17 08:51
@apeteri do you think you can provide a small reproducer as an itest for this so we can investigate further?

**Comment by ghillairet** [comment] 2021-09-17 09:33
@apeteri Exactly I was going to comment on it as I made it work like that.
My use case was building a product that references features available in repositories available in artifactory. If I have features only listed in the product file or in other features then it fails. If I reference a plugin from these artifactory repositories inside the product plugin for ex, then it works.

**Comment by apeteri** [comment] 2021-09-17 10:36
I re-used the example from #30, it tries to build a product that references a feature in an mvn zipped update site. This comes from an Apache-licensed project that I found in central. On 2.5.0-SNAPSHOT the stack trace looks like the following:

```
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-p2-repository-plugin:2.5.0-SNAPSHOT:assemble-repository (default-assemble-repository) on project issue271: Execution default-assemble-repository of goal org.eclipse.tycho:tycho-p2-repository-plugin:2.5.0-SNAPSHOT:assemble-repository failed: Load repository from url mvn:eu.scasefp7.eclipse:s-case-core-update-site:1.1.0:zip failed (org.eclipse.equinox.p2.core.ProvisionException: No repository found at mvn:eu.scasefp7.eclipse:s-case-core-update-site:1.1.0:zip.) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.eclipse.tycho:tycho-p2-repository-plugin:2.5.0-SNAPSHOT:assemble-repository (default-assemble-repository) on project issue271: Execution default-assemble-repository of goal org.eclipse.tycho:tycho-p2-repository-plugin:2.5.0-SNAPSHOT:assemble-repository failed: Load repository from url mvn:eu.scasefp7.eclipse:s-case-core-update-site:1.1.0:zip failed (org.eclipse.equinox.p2.core.ProvisionException: No repository found at mvn:eu.scasefp7.eclipse:s-case-core-update-site:1.1.0:zip.)
[...]
Caused by: java.lang.RuntimeException: Load repository from url mvn:eu.scasefp7.eclipse:s-case-core-update-site:1.1.0:zip failed (org.eclipse.equinox.p2.core.ProvisionException: No repository found at mvn:eu.scasefp7.eclipse:s-case-core-update-site:1.1.0:zip.)
    at org.eclipse.tycho.repository.p2base.artifact.repository.RepositoryArtifactProvider.loadRepository (RepositoryArtifactProvider.java:118)
    at org.eclipse.tycho.repository.p2base.artifact.repository.LazyArtifactRepository.getDelegate (LazyArtifactRepository.java:50)
    at org.eclipse.tycho.repository.p2base.artifact.repository.LazyArtifactRepository.contains (LazyArtifactRepository.java:87)
    at org.eclipse.tycho.repository.p2base.artifact.repository.RepositoryArtifactProvider.contains (RepositoryArtifactProvider.java:137)
    at org.eclipse.tycho.repository.local.MirroringArtifactProvider.contains (MirroringArtifactProvider.java:110)
    at org.eclipse.tycho.repository.p2base.artifact.provider.CompositeArtifactProvider.contains (CompositeArtifactProvider.java:59)
    at org.eclipse.tycho.repository.p2base.artifact.provider.CompositeArtifactProvider.getArtifactFile (CompositeArtifactProvider.java:86)
    at org.eclipse.tycho.p2.target.TargetPlatformBaseImpl.getLocalArtifactFile (TargetPlatformBaseImpl.java:130)
    at org.eclipse.tycho.p2.resolver.DefaultP2ResolutionResult.lambda$0 (DefaultP2ResolutionResult.java:58)
    at org.eclipse.tycho.p2.resolver.DefaultP2ResolutionResultEntry.getLocation (DefaultP2ResolutionResultEntry.java:73)
    at org.eclipse.tycho.p2.resolver.P2DependencyResolver.lambda$newDefaultTargetPlatform$2 (P2DependencyResolver.java:450)
    at org.eclipse.tycho.core.osgitools.targetplatform.ArtifactCollection.lambda$addArtifactFile$2 (ArtifactCollection.java:66)
    at org.eclipse.tycho.core.osgitools.DefaultArtifactDescriptor.getLocation (DefaultArtifactDescriptor.java:62)
    at org.eclipse.tycho.core.osgitools.targetplatform.ArtifactCollection.lambda$addArtifact$3 (ArtifactCollection.java:121)
    at org.eclipse.tycho.core.osgitools.DefaultArtifactDescriptor.getLocation (DefaultArtifactDescriptor.java:62)
    at org.eclipse.tycho.core.osgitools.targetplatform.ArtifactCollection.lambda$addArtifact$3 (ArtifactCollection.java:121)
    at org.eclipse.tycho.core.osgitools.DefaultArtifactDescriptor.getLocation (DefaultArtifactDescriptor.java:62)
    at org.eclipse.tycho.p2.facade.RepositoryReferenceTool.lambda$addTargetPlatformRepository$0 (RepositoryReferenceTool.java:130)
    at java.util.ArrayList.forEach (ArrayList.java:1540)
    at org.eclipse.tycho.p2.facade.RepositoryReferenceTool.addTargetPlatformRepository (RepositoryReferenceTool.java:130)
    at org.eclipse.tycho.p2.facade.RepositoryReferenceTool.getVisibleRepositories (RepositoryReferenceTool.java:98)
    at org.eclipse.tycho.plugins.p2.repository.AssembleRepositoryMojo.getVisibleRepositories (AssembleRepositoryMojo.java:193)
    at org.eclipse.tycho.plugins.p2.repository.AssembleRepositoryMojo.execute (AssembleRepositoryMojo.java:155)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:972)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: org.eclipse.equinox.p2.core.ProvisionException: No repository found at mvn:eu.scasefp7.eclipse:s-case-core-update-site:1.1.0:zip.
    at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.fail (AbstractRepositoryManager.java:397)
    at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository (AbstractRepositoryManager.java:701)
    at org.eclipse.equinox.internal.p2.artifact.repository.ArtifactRepositoryManager.loadRepository (ArtifactRepositoryManager.java:131)
    at org.eclipse.equinox.internal.p2.artifact.repository.ArtifactRepositoryManager.loadRepository (ArtifactRepositoryManager.java:125)
    at org.eclipse.tycho.p2.remote.RemoteArtifactRepositoryManager.loadRepository (RemoteArtifactRepositoryManager.java:105)
    at org.eclipse.tycho.repository.p2base.artifact.repository.RepositoryArtifactProvider.loadRepository (RepositoryArtifactProvider.java:116)
    at org.eclipse.tycho.repository.p2base.artifact.repository.LazyArtifactRepository.getDelegate (LazyArtifactRepository.java:50)
    at org.eclipse.tycho.repository.p2base.artifact.repository.LazyArtifactRepository.contains (LazyArtifactRepository.java:87)
    at org.eclipse.tycho.repository.p2base.artifact.repository.RepositoryArtifactProvider.contains (RepositoryArtifactProvider.java:137)
    at org.eclipse.tycho.repository.local.MirroringArtifactProvider.contains (MirroringArtifactProvider.java:110)
    at org.eclipse.tycho.repository.p2base.artifact.provider.CompositeArtifactProvider.contains (CompositeArtifactProvider.java:59)
    at org.eclipse.tycho.repository.p2base.artifact.provider.CompositeArtifactProvider.getArtifactFile (CompositeArtifactProvider.java:86)
    at org.eclipse.tycho.p2.target.TargetPlatformBaseImpl.getLocalArtifactFile (TargetPlatformBaseImpl.java:130)
    at org.eclipse.tycho.p2.resolver.DefaultP2ResolutionResult.lambda$0 (DefaultP2ResolutionResult.java:58)
    at org.eclipse.tycho.p2.resolver.DefaultP2ResolutionResultEntry.getLocation (DefaultP2ResolutionResultEntry.java:73)
    at org.eclipse.tycho.p2.resolver.P2DependencyResolver.lambda$newDefaultTargetPlatform$2 (P2DependencyResolver.java:450)
    at org.eclipse.tycho.core.osgitools.targetplatform.ArtifactCollection.lambda$addArtifactFile$2 (ArtifactCollection.java:66)
    at org.eclipse.tycho.core.osgitools.DefaultArtifactDescriptor.getLocation (DefaultArtifactDescriptor.java:62)
    at org.eclipse.tycho.core.osgitools.targetplatform.ArtifactCollection.lambda$addArtifact$3 (ArtifactCollection.java:121)
    at org.eclipse.tycho.core.osgitools.DefaultArtifactDescriptor.getLocation (DefaultArtifactDescriptor.java:62)
    at org.eclipse.tycho.core.osgitools.targetplatform.ArtifactCollection.lambda$addArtifact$3 (ArtifactCollection.java:121)
    at org.eclipse.tycho.core.osgitools.DefaultArtifactDescriptor.getLocation (DefaultArtifactDescriptor.java:62)
    at org.eclipse.tycho.p2.facade.RepositoryReferenceTool.lambda$addTargetPlatformRepository$0 (RepositoryReferenceTool.java:130)
    at java.util.ArrayList.forEach (ArrayList.java:1540)
    at org.eclipse.tycho.p2.facade.RepositoryReferenceTool.addTargetPlatformRepository (RepositoryReferenceTool.java:130)
    at org.eclipse.tycho.p2.facade.RepositoryReferenceTool.getVisibleRepositories (RepositoryReferenceTool.java:98)
    at org.eclipse.tycho.plugins.p2.repository.AssembleRepositoryMojo.getVisibleRepositories (AssembleRepositoryMojo.java:193)
    at org.eclipse.tycho.plugins.p2.repository.AssembleRepositoryMojo.execute (AssembleRepositoryMojo.java:155)
```

**Comment by laeubi** [comment] 2021-09-19 07:12
The problem here is that in 
`org.eclipse.tycho.osgi.configuration.MavenDependenciesResolverConfigurer.resolve(String, String, String, String, String, String, Collection<MavenArtifactRepositoryReference>)`
the session is null as the download is running in a different thread. While I see ways to inject the session in a `mojo` there seems to be no way for a component. @mickaelistria any idea how to solve this?

**Comment by laeubi** [comment] 2021-09-19 08:43
It seems the bes would be to allow passing the session as a parameter, that's how it is done in https://github.com/eclipse/tycho/pull/282 what makes the build succeed for the example given in https://github.com/eclipse/tycho/pull/279

**Closed** 2021-09-19 09:42 UTC
