### ISSUE TITLE
requires 'osgi.ee; (&(osgi.ee=JavaSE)(version=11))' but it could not be found

### ISSUE THREAD

**Issue by cdietrich** [eclipse/tycho#205] opened 2021-07-29 05:11 UTC
hi, i am trying to test mwe build with tycho 2.4
https://github.com/eclipse/mwe/compare/cd_tycho24
the build
```
 mvn \
                  -f maven/org.eclipse.emf.mwe2.parent/pom.xml \
                  -Dsign.skip=true \
                  -DtestFailureIgnore=true \
                  -Dmaven.javadoc.failOnError=false \
                  -Dtycho.localArtifacts=ignore \
                  -DBUILD_TYPE=N \
                  clean javadoc:aggregate-jar install
```

fails with

```
[INFO] Computing target platform for MavenProject: org.eclipse.emf:org.eclipse.emf.mwe.activities:1.6.2-SNAPSHOT @ /Users/cdietrich/MWE-master/git/mwe/plugins/org.eclipse.emf.mwe.activities/pom.xml
[ERROR] Cannot resolve target definition:
[ERROR]   Software being installed: org.eclipse.xpand 2.2.0.v201605260315
[ERROR]   Missing requirement: org.eclipse.equinox.common 3.15.0.v20210518-0604 requires 'osgi.ee; (&(osgi.ee=JavaSE)(version=11))' but it could not be found
[ERROR]   Cannot satisfy dependency: org.eclipse.core.runtime 3.22.0.v20210506-1025 depends on: osgi.bundle; org.eclipse.equinox.common [3.14.0,4.0.0)
[ERROR]   Cannot satisfy dependency: org.eclipse.emf.mwe.core 1.6.1.v20210218-2134 depends on: osgi.bundle; org.eclipse.core.runtime 0.0.0
[ERROR]   Cannot satisfy dependency: org.eclipse.xpand 2.2.0.v201605260315 depends on: osgi.bundle; org.eclipse.xtend 0.0.0
[ERROR]   Cannot satisfy dependency: org.eclipse.xtend 2.2.0.v201605260315 depends on: osgi.bundle; org.eclipse.emf.mwe.core 0.0.0
[ERROR]
[ERROR] Failed to resolve target definition /Users/cdietrich/MWE-master/git/mwe/maven/org.eclipse.emf.mwe2.target/org.eclipse.emf.mwe2.target.target: See log for details -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MavenExecutionException
```

although i run the build with
`echo $JAVA_HOME
/Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home/`

where are the know `'osgi.ee; (&(osgi.ee=JavaSE)(version=11))` configured/determined?

**Comment by laeubi** [comment] 2021-07-29 05:24
If you are using JustJ in your build, maybe #154 is related
if your are upgrading from 2.2>2.3 maybe #169 be related or #135

**Comment by cdietrich** [comment] 2021-07-29 05:25
is justj and explicit or implicit choice? can it somehow be pulled automatically?

**Comment by cdietrich** [comment] 2021-07-29 05:27
i have found

```
i have found
```
					<dependency-resolution>
						<extraRequirements>
							<requirement>
								<type>eclipse-feature</type>
								<id>org.eclipse.jdt</id>
								<versionRange>0.0.0</versionRange>
							</requirement>
						</extraRequirements>
					</dependency-resolution>
					<executionEnvironment>JavaSE-1.8</executionEnvironment>
				</configuration>
```
```

**Comment by laeubi** [comment] 2021-07-29 05:28
There are some complains that justj gets pulled in in some eclipse-upgrade scenarios but not sure what the cause is.

If you specify

`<executionEnvironment>JavaSE-1.8</executionEnvironment>`

this might interfere here but @mickaelistria could tell more here.

**Comment by cdietrich** [comment] 2021-07-29 05:32
indeed, if i specify
`<executionEnvironment>JavaSE-11</executionEnvironment>`
additionally, it seems to work.

**Comment by laeubi** [comment] 2021-07-29 05:34
Actually I would expect that specifying `executionEnvironment` is not necessary here. Do you still think this is a bug or can we close the issue?

**Comment by cdietrich** [comment] 2021-07-29 05:35
i dont know why the java 8 is there in the first place. need to dig in history.

**Comment by mickaelistria** [comment] 2021-07-29 08:46
Setting Java 8 as executionEnvironment makes p2 only include Java 8 unit independency resolution.  Failure to resolve incompatible osgi.ee requirements is expected and desired, and not an issue.

**Closed by mickaelistria** 2021-07-29 08:46 UTC
