### ISSUE TITLE
Problems with Tycho 2.7.2 in xtext

### ISSUE THREAD

**Issue by cdietrich** [eclipse/tycho#910] opened 2022-04-22 14:09 UTC
with tycho 2.7.2 some of our tests in xtext no longer seem to be executed

``` 
/surefire.properties, -pluginCustomization, /home/jenkins/agent/workspace/xtext-eclipse_cd_testTycho272/org.eclipse.xtext.xbase.ui.tests/../releng/org.eclipse.xtext.tycho.tests.parent/pluginCustomization.ini, -timeout, 2400000]
15:31:58  java.lang.RuntimeException: Bundle org.eclipse.xtext.xbase.ui.tests is not found
```
any idea what could cause this?
https://ci.eclipse.org/xtext/job/xtext-eclipse/job/cd_testTycho272/2/consoleFull

**Comment by cdietrich** [comment] 2022-04-22 14:11
https://ci.eclipse.org/xtext/job/xtext-eclipse/job/cd_testTycho272/2/artifact/org.eclipse.xtext.xbase.ui.tests/target/work/data/.metadata/.log 
indicates a pde problem.
shouldnt the build be marked as failed then?

**Comment by cdietrich** [comment] 2022-04-22 14:12
problem seems to be independent from new tycho version. so i dont know if this ever worked
(aka tests failed)

**Comment by cdietrich** [comment] 2022-04-22 14:15
https://github.com/eclipse/xtext-eclipse/issues/1842

**Comment by laeubi** [comment] 2022-04-22 14:18
> problem seems to be independent from new tycho version.

Can we close this issue then? I left you a comment about why the build do not fails in the linked issue.

**Comment by cdietrich** [comment] 2022-04-22 14:20
i have no idea how this is intended to work and how to find out why test plugin cannot be found/activated

**Comment by laeubi** [comment] 2022-04-22 14:21
Your test has use-contraint violations:

```
Chain 1:
  org.eclipse.pde.api.tools [osgi.identity; osgi.identity="org.eclipse.pde.api.tools"; type="osgi.bundle"; version:Version="1.2.900.v20220411-2005"; singleton:="true"]
    require: (&(osgi.wiring.bundle=org.objectweb.asm)(&(bundle-version>=9.3.0)(!(bundle-version>=10.0.0))))
     |
    provide: osgi.wiring.bundle: org.objectweb.asm
  org.objectweb.asm [osgi.identity; osgi.identity="org.objectweb.asm"; type="osgi.bundle"; version:Version="9.3.0"]

Chain 2:
  org.eclipse.pde.api.tools [osgi.identity; osgi.identity="org.eclipse.pde.api.tools"; type="osgi.bundle"; version:Version="1.2.900.v20220411-2005"; singleton:="true"]
    require: (&(osgi.wiring.bundle=org.objectweb.asm.tree)(&(bundle-version>=9.2.0)(!(bundle-version>=10.0.0))))
     |
    provide: osgi.wiring.bundle; bundle-version:Version="9.2.0.v20210813-1119"; osgi.wiring.bundle="org.objectweb.asm.tree"
  org.objectweb.asm.tree [osgi.identity; osgi.identity="org.objectweb.asm.tree"; type="osgi.bundle"; version:Version="9.2.0.v20210813-1119"]
    import: (&(osgi.wiring.package=org.objectweb.asm)(&(version>=9.2.0)(!(version>=9.3.0))))
     |
    export: osgi.wiring.package: org.objectweb.asm
  org.objectweb.asm [osgi.identity; osgi.identity="org.objectweb.asm"; type="osgi.bundle"; version:Version="9.2.0.v20210813-1119"]
	at org.eclipse.osgi.container.Module.start(Module.java:463)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1847)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1840)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1781)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1745)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1667)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)
```

**Comment by cdietrich** [comment] 2022-04-22 14:23
Yes but these are not there in previous builds with the same problem

**Comment by cdietrich** [comment] 2022-04-22 14:24
https://ci.eclipse.org/xtext/job/xtext-eclipse/job/master/2430/

**Comment by laeubi** [comment] 2022-04-22 14:26
Maybe due to updated P2 version now the resoloution is slightly different, but I don't know enough about xtext and the test, you probably should exclude asm 9.2.0 from your test code or ask the `org.eclipse.pde.api.tools` to use more consitent import ranges, I have no idea why one wants imports org.objectweb.asm with Version 9.3+ but org.objectweb.asm.tree with 9.2+ ... 

Problem here is also maybe with the asm itself as it has no proper use-contraints on its export package maybe (haven't checked in details) ...

**Comment by cdietrich** [comment] 2022-04-22 14:31
We still use 9.2 Cause orbit m2 is not out yet 
But shouldn’t ask 93 then be pulled by pde if it needs it ?

**Comment by laeubi** [comment] 2022-04-22 14:33
The problem is that currently **both** are pulled in and this leads to a conflicting resolution! Can't you consume the one from PDE/Platform as it seems it is already part of your build?

**Comment by cdietrich** [comment] 2022-04-22 14:36
I want to pull consistent in oomph so I can’t

**Comment by cdietrich** [comment] 2022-04-22 14:37
And we have to wait for m2 of orbit or get rid of pde api tools dep

**Comment by laeubi** [comment] 2022-04-22 15:07
Alright I'll close this for now as it is not an tycho issue, let us know if the M2 is out and you still see issues.

**Closed by laeubi** 2022-04-22 15:07 UTC
