### ISSUE TITLE
org.eclipse.tycho:tycho-packaging-plugin:2.7.3:package-plugin issuing error <<pluginname>>/target/classes does not exist

### ISSUE THREAD

**Issue by SatishChGit** [eclipse/tycho#1093] opened 2022-06-29 12:05 UTC
Hi Team,

We have a product depends on eclipse framework and building this with maven tycho plugin. We want to migrate to tycho plugin to 2.7.3 as we are upgrading to use eclipse 2022-03. But this version of tycho plugin is giving error for couple of plugins which doesn't have source code. 

ERROR] Failed to execute goal org.eclipse.tycho:tycho-packaging-plugin:2.7.3:package-plugin (default-package-plugin) on project <<pluginname>>: Execution default-package-plugin of goal org.eclipse.tycho:tycho-packaging-plugin:2.7.3:package-plugin failed: basedir <<pluginname>>/target/classes does not exist

![image](https://user-images.githubusercontent.com/23031170/176432193-0219592a-75a5-4dfe-b742-9980685e088b.png)

**Comment by akurtakov** [comment] 2022-06-29 12:43
Would you please provide minimal reproducer we can look at? There are a number of bundles without classes in Eclipse Platform that build just fine (e.g. https://github.com/eclipse-platform/eclipse.platform.common/blob/master/bundles/org.eclipse.platform.doc.tips/pom.xml) so we need more details to be able to say what goes wrong for you.

**Comment by laeubi** [comment] 2022-06-29 12:54
By the way, both build.properties also META-INF are showing error markers (**which Tycho might treat as errors**).

**Comment by howlger** [comment] 2022-07-25 15:35
I faced the same, at least in my case misleading, error message caused by a missing `,` in `build.properties`, e.g.

```
bin.includes = META-INF/\
               plugin.properties
```
instead of
```
bin.includes = META-INF/,\
               plugin.properties
```
Correcting `build.properties` fixed it for me.

**Comment by howlger** [comment] 2022-07-25 16:12
> > The same misleading error message I get for a non-existing `bin.includes` file, e.g.
> 
> Why is it misleading to tell you a non exiting file does not exits?

When `bin.includes` contains a file that does not exist, Maven log says `.../target/classes does not exist` (tested with a sample plugin not containing Java code):
```
...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for parent 1.0.0-SNAPSHOT:
[INFO] 
[INFO] parent ............................................. SUCCESS [  0.048 s]
[INFO] [bundle] Sample .................................... FAILURE [  0.729 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  4.296 s
[INFO] Finished at: 2022-07-25T18:11:02+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-packaging-plugin:2.7.3:package-plugin (default-package-plugin) on project sample: Execution default-package-plugin of goal org.eclipse.tycho:tycho-packaging-plugin:2.7.3:package-plugin failed: basedir C:\Users\Howlger\git\tycho_issues_1093\sample\target\classes does not exist -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :sample
```

**Comment by laeubi** [comment] 2022-07-25 16:17
@howlger can you provide an [integration-test](https://github.com/eclipse/tycho/wiki#providing-an-integration-test) to demonstrate the issue? I assume this happens when there is not a single class file compiled.

**Comment by howlger** [comment] 2022-07-26 06:58
> @howlger can you provide an [integration-test](https://github.com/eclipse/tycho/wiki#providing-an-integration-test) to demonstrate the issue? I assume this happens when there is not a single class file compiled.

See https://github.com/eclipse/tycho/pull/1196

**Comment by laeubi** [comment] 2022-07-26 17:29
This will be fixed in the next snapshot build, thanks for the test-case!

**Closed** 2022-07-26 17:29 UTC
Labels: needs info, test case required

**Comment by howlger** [comment] 2022-07-26 20:37
Thanks @laeubi for the quick response and for improving the error message. It's great that you take your time to do things like this besides driving Tycho innovation. Nice to see you've become a committer on PDE as well.

**Comment by laeubi** [comment] 2022-07-27 06:01
No problem, I think in this case deriving the test case was much more work as the fix :-)
