### ISSUE TITLE
New Equinox Resolver in Tycho 2.3.x and above fails to resolve in aceptable time in certein situations

### ISSUE THREAD

**Issue by laeubi** [eclipse/tycho#213] opened 2021-08-06 08:21 UTC
This is a summary ticket for a problem reported already in the following tickets:

- https://github.com/eclipse/tycho/issues/212
- https://github.com/eclipse/tycho/issues/197

The issue here is, that in certain situations tycho creates a resolver task that seems incredible hard to resolve. A very good example project could be found [here](https://github.com/eclipse/tycho/files/6922395/hanging_project.zip) from the issue #212. The project is very simple (only one bundle), does not contain any special configuration (plain updatesites, only two standard envs) and also the bundle itself has no special requirements (just a few simple bundle imports).

It still results in a massive resolve operation that takes up to 6 minutes! A profiling session reveals that there are millions of calls to ModuleContainerAdaptor, while the similar ipt01 tycho project just has a few hundreds of them. As even though the average time is low, the plain number of calls makes this very slow and at least in #197 results in crashes due to out-of-memory.

![profiling](https://user-images.githubusercontent.com/1331477/128478621-5906d77f-f6eb-4bf6-9449-a735f9844546.png)

Maybe @mickaelistria can tell a bit more if this is an issue of Tycho, it might even be an issue of equinox or Apache Felix Resolver used by equinox.

**Comment by mickaelistria** [comment] 2021-08-17 11:58
I've enabled extra logging for the resolver (this needs to be achieved through code by settings some debugOptions to the ModuleContainerAdapter in EquinoxResolver). It shows lots of lines of computation and, more interesting, warning reports. Here is a subset, but about all log is variation of that:

> 
> RESOLVER: Candidate permutation failed due to a conflict between imports; will try another if possible. (Uses constraint violation. Unable to resolve resource com.sample.hanging.bundle [osgi.identity; osgi.identity="com.sample.hanging.bundle"; type="osgi.bundle"; version:Version="1.0.0.qualifier"; singleton:="true"] because it is exposed to package 'com.sun.istack' from resources com.sun.xml.bind.jaxb-impl [osgi.identity; osgi.identity="com.sun.xml.bind.jaxb-impl"; type="osgi.bundle"; version:Version="2.3.3"] and com.sun.xml.bind [osgi.identity; osgi.identity="com.sun.xml.bind"; type="osgi.bundle"; version:Version="2.3.3.v20201118-1818"] via two dependency chains.
> 
> Chain 1:
>   com.sample.hanging.bundle [osgi.identity; osgi.identity="com.sample.hanging.bundle"; type="osgi.bundle"; version:Version="1.0.0.qualifier"; singleton:="true"]
>     require: (osgi.wiring.bundle=com.sun.xml.bind.jaxb-impl)
>      |
>     provide: osgi.wiring.bundle: com.sun.xml.bind.jaxb-impl
>   com.sun.xml.bind.jaxb-impl [osgi.identity; osgi.identity="com.sun.xml.bind.jaxb-impl"; type="osgi.bundle"; version:Version="2.3.3"]
> 
> Chain 2:
>   com.sample.hanging.bundle [osgi.identity; osgi.identity="com.sample.hanging.bundle"; type="osgi.bundle"; version:Version="1.0.0.qualifier"; singleton:="true"]
>     require: (osgi.wiring.bundle=com.sun.xml.bind.jaxb-impl)
>      |
>     provide: osgi.wiring.bundle; bundle-version:Version="2.3.3"; osgi.wiring.bundle="com.sun.xml.bind.jaxb-impl"
>   com.sun.xml.bind.jaxb-impl [osgi.identity; osgi.identity="com.sun.xml.bind.jaxb-impl"; type="osgi.bundle"; version:Version="2.3.3"]
>     import: (&(osgi.wiring.package=com.sun.xml.bind.v2.runtime.reflect)(&(version>=2.3.0)(!(version>=3.0.0))))
>      |
>     export: osgi.wiring.package=com.sun.xml.bind.v2.runtime.reflect; uses:=com.sun.xml.bind.api
>   com.sun.xml.bind [osgi.identity; osgi.identity="com.sun.xml.bind"; type="osgi.bundle"; version:Version="2.3.3.v20201118-1818"]
>     import: (&(osgi.wiring.package=com.sun.xml.bind.api)(&(version>=2.3.0)(!(version>=3.0.0))))
>      |
>     export: osgi.wiring.package=com.sun.xml.bind.api; uses:=com.sun.xml.bind.v2.model.annotation
>   com.sun.xml.bind [osgi.identity; osgi.identity="com.sun.xml.bind"; type="osgi.bundle"; version:Version="2.3.3.v20201118-1818"]
>     import: (&(osgi.wiring.package=com.sun.xml.bind.v2.model.annotation)(&(version>=2.3.0)(!(version>=3.0.0))))
>      |
>     export: osgi.wiring.package=com.sun.xml.bind.v2.model.annotation; uses:=com.sun.xml.bind.v2.model.core
>   com.sun.xml.bind [osgi.identity; osgi.identity="com.sun.xml.bind"; type="osgi.bundle"; version:Version="2.3.3.v20201118-1818"]
>     import: (&(osgi.wiring.package=com.sun.xml.bind.v2.model.core)(&(version>=2.3.0)(!(version>=3.0.0))))
>      |
>     export: osgi.wiring.package=com.sun.xml.bind.v2.model.core; uses:=com.sun.xml.bind.v2.model.impl
>   com.sun.xml.bind [osgi.identity; osgi.identity="com.sun.xml.bind"; type="osgi.bundle"; version:Version="2.3.3.v20201118-1818"]
>     import: (&(osgi.wiring.package=com.sun.xml.bind.v2.model.impl)(&(version>=2.3.0)(!(version>=3.0.0))))
>      |
>     export: osgi.wiring.package=com.sun.xml.bind.v2.model.impl; uses:=com.sun.xml.bind.v2.model.nav
>   com.sun.xml.bind [osgi.identity; osgi.identity="com.sun.xml.bind"; type="osgi.bundle"; version:Version="2.3.3.v20201118-1818"]
>     import: (&(osgi.wiring.package=com.sun.xml.bind.v2.model.nav)(&(version>=2.3.0)(!(version>=3.0.0))))
>      |
>     export: osgi.wiring.package=com.sun.xml.bind.v2.model.nav; uses:=com.sun.xml.bind.v2.runtime
>   com.sun.xml.bind [osgi.identity; osgi.identity="com.sun.xml.bind"; type="osgi.bundle"; version:Version="2.3.3.v20201118-1818"]
>     import: (&(osgi.wiring.package=com.sun.xml.bind.v2.runtime)(&(version>=2.3.0)(!(version>=3.0.0))))
>      |
>     export: osgi.wiring.package=com.sun.xml.bind.v2.runtime; uses:=com.sun.istack
>   com.sun.xml.bind [osgi.identity; osgi.identity="com.sun.xml.bind"; type="osgi.bundle"; version:Version="2.3.3.v20201118-1818"]
>     import: (&(osgi.wiring.package=com.sun.istack)(&(version>=2.3.0)(!(version>=3.0.0))))
>      |
>     export: osgi.wiring.package: com.sun.istack
>   com.sun.xml.bind [osgi.identity; osgi.identity="com.sun.xml.bind"; type="osgi.bundle"; version:Version="2.3.3.v20201118-1818"])
> 
> RESOLVER: Candidate permutation failed due to a conflict between imports; will try another if possible. (Uses constraint violation. Unable to resolve resource org.eclipse.tools.templates.freemarker [osgi.identity; osgi.identity="org.eclipse.tools.templates.freemarker"; type="osgi.bundle"; version:Version="1.2.100.202011191931"] because it is exposed to package 'com.sun.xml.bind.v2.model.core' from resources com.sun.xml.bind [osgi.identity; osgi.identity="com.sun.xml.bind"; type="osgi.bundle"; version:Version="2.3.3.v20201118-1818"] and com.sun.xml.bind.jaxb-impl [osgi.identity; osgi.identity="com.sun.xml.bind.jaxb-impl"; type="osgi.bundle"; version:Version="2.3.3"] via two dependency chains.
> 
> Chain 1:
>   org.eclipse.tools.templates.freemarker [osgi.identity; osgi.identity="org.eclipse.tools.templates.freemarker"; type="osgi.bundle"; version:Version="1.2.100.202011191931"]
>     require: (&(osgi.wiring.bundle=com.sun.xml.bind)(&(bundle-version>=2.3.3)(!(bundle-version>=3.0.0))))
>      |
>     provide: osgi.wiring.bundle: com.sun.xml.bind
>   com.sun.xml.bind [osgi.identity; osgi.identity="com.sun.xml.bind"; type="osgi.bundle"; version:Version="2.3.3.v20201118-1818"]
> 
> Chain 2:
>   org.eclipse.tools.templates.freemarker [osgi.identity; osgi.identity="org.eclipse.tools.templates.freemarker"; type="osgi.bundle"; version:Version="1.2.100.202011191931"]
>     require: (&(osgi.wiring.bundle=com.sun.xml.bind)(&(bundle-version>=2.3.3)(!(bundle-version>=3.0.0))))
>      |
>     provide: osgi.wiring.bundle; bundle-version:Version="2.3.3.v20201118-1818"; osgi.wiring.bundle="com.sun.xml.bind"
>   com.sun.xml.bind.jaxb-impl [osgi.identity; osgi.identity="com.sun.xml.bind.jaxb-impl"; type="osgi.bundle"; version:Version="2.3.3"]
>     import: (&(osgi.wiring.package=com.sun.xml.bind.v2.runtime.reflect)(&(version>=2.3.0)(!(version>=3.0.0))))
>      |
>     export: osgi.wiring.package=com.sun.xml.bind.v2.runtime.reflect; uses:=com.sun.xml.bind.api
>   com.sun.xml.bind [osgi.identity; osgi.identity="com.sun.xml.bind"; type="osgi.bundle"; version:Version="2.3.3.v20201118-1818"]
>     import: (&(osgi.wiring.package=com.sun.xml.bind.api)(&(version>=2.3.0)(!(version>=3.0.0))))
>      |
>     export: osgi.wiring.package=com.sun.xml.bind.api; uses:=com.sun.xml.bind.v2.model.annotation
>   com.sun.xml.bind [osgi.identity; osgi.identity="com.sun.xml.bind"; type="osgi.bundle"; version:Version="2.3.3.v20201118-1818"]
>     import: (&(osgi.wiring.package=com.sun.xml.bind.v2.model.annotation)(&(version>=2.3.0)(!(version>=3.0.0))))
>      |
>     export: osgi.wiring.package=com.sun.xml.bind.v2.model.annotation; uses:=com.sun.xml.bind.v2.model.core
>   com.sun.xml.bind [osgi.identity; osgi.identity="com.sun.xml.bind"; type="osgi.bundle"; version:Version="2.3.3.v20201118-1818"]
>     import: (&(osgi.wiring.package=com.sun.xml.bind.v2.model.core)(&(version>=2.3.0)(!(version>=3.0.0))))
>      |
>     export: osgi.wiring.package=com.sun.xml.bind.v2.model.core; uses:=com.sun.xml.bind.v2.model.impl
>   com.sun.xml.bind [osgi.identity; osgi.identity="com.sun.xml.bind"; type="osgi.bundle"; version:Version="2.3.3.v20201118-1818"]
>     import: (&(osgi.wiring.package=com.sun.xml.bind.v2.model.impl)(&(version>=2.3.0)(!(version>=3.0.0))))
>      |
>     export: osgi.wiring.package=com.sun.xml.bind.v2.model.impl; uses:=com.sun.xml.bind.v2.model.nav
>   com.sun.xml.bind [osgi.identity; osgi.identity="com.sun.xml.bind"; type="osgi.bundle"; version:Version="2.3.3.v20201118-1818"]
>     import: (&(osgi.wiring.package=com.sun.xml.bind.v2.model.nav)(&(version>=2.3.0)(!(version>=3.0.0))))
>      |
>     export: osgi.wiring.package=com.sun.xml.bind.v2.model.nav; uses:=com.sun.xml.bind.v2.runtime
>   com.sun.xml.bind [osgi.identity; osgi.identity="com.sun.xml.bind"; type="osgi.bundle"; version:Version="2.3.3.v20201118-1818"]
>     import: (&(osgi.wiring.package=com.sun.xml.bind.v2.runtime)(&(version>=2.3.0)(!(version>=3.0.0))))
>      |
>     export: osgi.wiring.package=com.sun.xml.bind.v2.runtime; uses:=com.sun.xml.bind.v2.runtime.property
>   com.sun.xml.bind [osgi.identity; osgi.identity="com.sun.xml.bind"; type="osgi.bundle"; version:Version="2.3.3.v20201118-1818"]
>     import: (&(osgi.wiring.package=com.sun.xml.bind.v2.runtime.property)(&(version>=2.3.0)(!(version>=3.0.0))))
>      |
>     export: osgi.wiring.package=com.sun.xml.bind.v2.runtime.property; uses:=com.sun.xml.bind.v2.util
>   com.sun.xml.bind [osgi.identity; osgi.identity="com.sun.xml.bind"; type="osgi.bundle"; version:Version="2.3.3.v20201118-1818"]
>     import: (&(osgi.wiring.package=com.sun.xml.bind.v2.util)(&(version>=2.3.0)(!(version>=3.0.0))))
>      |
>     export: osgi.wiring.package=com.sun.xml.bind.v2.util; uses:=com.sun.xml.bind.v2.runtime.unmarshaller
>   com.sun.xml.bind.jaxb-impl [osgi.identity; osgi.identity="com.sun.xml.bind.jaxb-impl"; type="osgi.bundle"; version:Version="2.3.3"]
>     import: (&(osgi.wiring.package=com.sun.xml.bind.v2.runtime.unmarshaller)(&(version>=2.3.0)(!(version>=3.0.0))))
>      |
>     export: osgi.wiring.package=com.sun.xml.bind.v2.runtime.unmarshaller; uses:=com.sun.xml.bind.v2.model.core
>   com.sun.xml.bind.jaxb-impl [osgi.identity; osgi.identity="com.sun.xml.bind.jaxb-impl"; type="osgi.bundle"; version:Version="2.3.3"]
>     import: (&(osgi.wiring.package=com.sun.xml.bind.v2.model.core)(&(version>=2.3.0)(!(version>=3.0.0))))
>      |
>     export: osgi.wiring.package: com.sun.xml.bind.v2.model.core
>   com.sun.xml.bind.jaxb-impl [osgi.identity; osgi.identity="com.sun.xml.bind.jaxb-impl"; type="osgi.bundle"; version:Version="2.3.3"])


I'll try to reduce the test case to the bare minimal, and then will investigate whether issue is in Equinox or if there is something we're doing wrong in how we use the resolver API.

**Comment by laeubi** [comment] 2021-08-17 13:30
Can you try with @wimjongman s emaple to see if similar messages are emitted?

**Comment by mickaelistria** [comment] 2021-08-17 15:25
> Can you try with @wimjongman s emaple to see if similar messages are emitted?

I tried, the example is too big and shows *millions* of lines of log (taking a lot of time to print) before getting into an erroneous state; so I gave up.

**Comment by wimjongman** [comment] 2021-08-17 15:31
Did you see it hang after a while?

**Comment by mickaelistria** [comment] 2021-08-17 16:08
Reducing the pom to
```MF
Manifest-Version: 1.0
Bundle-ManifestVersion: 2
Bundle-SymbolicName: com.sample.hanging.bundle;singleton:=true
Bundle-Version: 1.0.0.qualifier
Bundle-RequiredExecutionEnvironment: JavaSE-11
Require-Bundle: org.eclipse.tools.templates.freemarker;bundle-version="1.0.0",
 com.sun.xml.bind.jaxb-impl
```
allows to show the issue (although it has less dependencies so resolver tries less permutations, so it's taking a ~1min15s with Tycho 2.4.0/2.5.0-SNAPSHOT instead of 10 seconds with Tycho 2.2.0).
It's not yet enough to identify the root cause, but that's on the right direction.

**Comment by mickaelistria** [comment] 2021-08-18 21:35
I have reduced the case to not depend on CDT bundles any more and still highlight the longer time to resolve: see 
[com.sample.hanging.zip](https://github.com/eclipse/tycho/files/7010305/com.sample.hanging.zip) . Note that times are not about several minutes any longer, but this is simply because we've reduced the number of bundles in the dependency tree, so reduced the number of permutation. But we still observe unexpected increased duration that can more easily be investigated and would hopefully lead to the root cause.

With this project, it also gives another hint:
```
$ mvn -o install
[...]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for parent 1.0.0-SNAPSHOT:
[INFO] 
[INFO] parent ............................................. SUCCESS [  0.068 s]
[INFO] com.sample.hanging.dep ............................. SUCCESS [  0.704 s]
[INFO] com.sample.hanging.bundle .......................... SUCCESS [  0.097 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  6.082 s
[INFO] Finished at: 2021-08-18T23:20:05+02:00
[INFO] ------------------------------------------------------------------------
```
so everything fast when inside reactor, but referencing the dependency bundle from outside of the reactor (local repo in that case)
```
$ mvn -o validate -f com.sample.hanging.bundle
[,,,]
[WARNING] The following locally built units have been used to resolve project dependencies:
[WARNING]   com.sample.hanging.dep/1.0.0.202108182119
[...]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  27.262 s
[INFO] Finished at: 2021-08-18T23:20:34+02:00
[INFO] ------------------------------------------------------------------------
```
Shows that this becomes a much longer execution, in the resolution step. Similar logs from resolution as the one mentioned previously can be shown.

So it could be that the fact that dep is zipped or is a reactor module makes a huge difference.

**Comment by HannesWell** [comment] 2021-08-22 20:53
Maybe this is helpful:
I also sampled the example of issue #212 and found the following results, which shows that most of the time is spend in `ResolverImpl.mergeUses()`.

![grafik](https://user-images.githubusercontent.com/44067969/130369593-25c6ee8a-d54d-4dd8-b6d3-c4ee08d44ef0.png)

Expanding the item for the mergeUses() method shows the following entries:

![grafik](https://user-images.githubusercontent.com/44067969/130369727-b5ecd746-dcdd-4705-801e-c047c29615ef.png)

From this I assume that either (too) many uses directives are used or the implementation in ResolverImpl should be improved.

**Comment by mickaelistria** [comment] 2021-08-23 08:20
The uses directive is indeed what cause extra computation. However, it should resolve in a manageable time. See my previous comment: the resolution time seems to be heavily influenced on whether the dependency is in the reactor or is only a p2 dependency; however this "origin" doesn't change the number of `use` constraints that are to be handled. So the `use` per se seems to be resolveable quite quickly in a "good" scenario (reactor) but not in a bad scenario (external dep)

**Comment by mickaelistria** [comment] 2021-08-30 09:49
> actually I think the problem is: `Resolving root bundle: osgi.identity; osgi.identity="com.sun.xml.bind"; type="osgi.bundle"; version:Version="2.3.3.v20201118-1818" Resolving root bundle: osgi.identity; osgi.identity="jakarta.xml.bind"; type="osgi.bundle"; version:Version="2.3.3.v20201118-1818"`
> [...]
> I would expect omitting one of the xml.bind providers would make this perfectly deployable. In

This combination indeed triggers the issue; but it is a real use-case (taken from the CDT one), so this needs to be supported I guess. I don't think people will like it if we say "Tycho doesn't work in this case".

> That's why I recently suggested to drop the resolver (or at least provide this as a configuration option) where we simply compute the access-rule directly.

IIRC, I asked that we start a dedicated ticket/discussion for it to evaluate the gain/loss before trying anything. Did you open one already?

**Comment by laeubi** [comment] 2021-08-30 10:29
> This combination indeed triggers the issue; but it is a real use-case (taken from the CDT one)

does the CDT product really contains both bundles?

>  this needs to be supported

I never said it shouldn't I just wanted to point out that what is tried to be build here actually could be deployed/used and is a valid bundle, so of course it should work.

> I asked that we start a dedicated ticket/discussion for it to evaluate the gain/loss

I created https://github.com/eclipse/tycho/discussions/249 right now.

**Comment by mickaelistria** [comment] 2021-08-30 12:11
It's not really a CDT product, the example I've built is a reduced (to the minimim content I identified) case of https://github.com/eclipse/tycho/issues/212 , I don't know much about the details.
But I guess that the other https://github.com/eclipse/tycho/issues/197 is from Mylyn, that does seem to contain or require both bundles.

**Comment by mickaelistria** [comment] 2021-09-03 08:21
If the cases where we have such long delay in Tycho are all cases when bundle wouldn't resolve in Equinox; shouldn't Tycho fail just like Equinox? I'm wondering whether there could be come settings to the resolver to allow an early failure just like with Equinox console.
cc @tjwatson do you have any idea or suggestion here?

**Comment by tjwatson** [comment] 2021-09-03 13:38
> If the cases where we have such long delay in Tycho are all cases when bundle wouldn't resolve in Equinox; shouldn't Tycho fail just like Equinox? I'm wondering whether there could be come settings to the resolver to allow an early failure just like with Equinox console.
> cc @tjwatson do you have any idea or suggestion here?

I would expect the resolution to fail the same in tycho here, although maybe some of the computation on the packages available from the JVM are different here.  For the framework we base the system bundle exports from the JVM by using the JPMS modules we discover in the boot layer.

The framework uses an executor which will allow the module resolver to do some work in parallel.  Not sure if that is contributing to the difference.  We return this executor from `org.eclipse.osgi.container.ModuleContainerAdaptor.getResolverExecutor()`

https://git.eclipse.org/c/equinox/rt.equinox.framework.git/tree/bundles/org.eclipse.osgi/container/src/org/eclipse/osgi/internal/framework/EquinoxContainerAdaptor.java#n125

Which by default will use the number of available processors for the number of threads used by the resolver operation.  If you are using the default `ModuleContainerAdaptor.getResolverExecutor()` implementation then the resolve operation is single threaded.

You could also try returning "1" for the property key "equinox.resolver.revision.batch.size" from your implementation of the method: `org.eclipse.osgi.container.ModuleContainerAdaptor.getProperty(String)`.  That is not what the framework does (it actually uses the max value so it tries to resolver all bundles "at once".  But if you try with a value of "1" it will drastically reduce the problem set the resolver is process because it will try to resolve one bundle at a time.

Finally:

> Only because there is some build time ambiguity does not mean it can't be deployed. e.g. in a linear compile classpath the first dependency will simply take precedence also compilers do not care much about class-space consistency.

If this is a true statement (I'm not sure it is) then you could consider having your ModuleRevision object constructed such that the ModuleCapability implementations always return null from `ModuleCapability.getDirectives().get("uses")`.

**Comment by mickaelistria** [comment] 2021-09-14 21:46
Thanks a lot @tjwatson , it looks like setting `equinox.resolver.revision.batch.size` to `1` does the trick and brings back same result and performance as what we were seeing using the old resolver in Tycho 2.2 and earlier. I admit I don't fully get how this has such a big impact, but I'm anyway very happy about it!
I'll start a PR with this change and if this works, I'll merge it ASAP to gather feedback.

**Comment by laeubi** [comment] 2021-09-15 04:11
Great news!

**Comment by laeubi** [comment] 2021-09-15 04:18
>  admit I don't fully get how this has such a big impact, but I'm anyway very happy about it!

Interestingly this was already mentioned [here](https://bugs.eclipse.org/bugs/show_bug.cgi?id=516664) back in 2017 so probably it would be good to better describe/document what this flag does and what are the impacts (e.g. if it really speeds up resolving why this is not the default @tjwatson?)

**Comment by mickaelistria** [comment] 2021-09-15 09:57
This should now be fixed in 2.5.0-SNAPSHOT. @katebambuk @wimjongman Please try newer 2.5.0-SNAPSHOT and report whether it works better for you.

**Closed by mickaelistria** 2021-09-15 09:57 UTC
Labels: bug, 🚨 regression, needs info

**Comment by tjwatson** [comment] 2021-09-15 13:14
> > admit I don't fully get how this has such a big impact, but I'm anyway very happy about it!
> 
> Interestingly this was already mentioned [here](https://bugs.eclipse.org/bugs/show_bug.cgi?id=516664) back in 2017 and [here](https://bugs.eclipse.org/bugs/show_bug.cgi?id=460393) at 2015, so probably it would be good to better describe/document what this flag does (I don't find any other references about it) and what are the impacts (e.g. if it really speeds up resolving why this is not the default @tjwatson? Even though the later bug indicates it should be the default....)

While we can surely document this.  I don't want to give the impression that such things are API.  I still think something else must be contributing to the issue here, my suspicion is the system bundle exports (from the JVM) are calculated differently.  The other thing that concerns me is that the resolve didn't timeout after the default 2 minutes.  I realize this is likely because your ModuleContainerAdaptor is taking the default implementation of: 

`org.eclipse.osgi.container.ModuleContainerAdaptor.getScheduledExecutor()`

That returns null by default which will disable the timeout of the resolution operation.  If you returned a ScheduledExecutor then the ModuleContainer will use that to put a future that will timeout and cancel the long running resolve operation, then it would default to falling back to resolving bundles one at a time.

The reason we do not use one at a time resolution in the framework by default is because there are scenarios where doing bundle resolution one at a time will lock the resolver decisions in place such that it cannot backtrack to find another, possibly, valid solution.  Instead we first try a "big bang" resolution that attempts to resolve all the unresolved bundles at one time because that gives the resolver more choice in finding the valid solution.  But that also gives the resolver more choice which can lead to a very long resolve times because the resolver has to search over more possible solutions before giving up.

If you do supply a ScheduledExecutor to the ModuleContainer then you can control the timeout length with the property `equinox.resolver.batch.timeout` which is in milliseconds.  I would recommend you try doing that and have a timeout you think is reasonable for tycho (e.g. 10 seconds?).

**Comment by laeubi** [comment] 2021-09-23 04:01
> If you returned a ScheduledExecutor then the ModuleContainer will use that to put a future that will timeout and cancel the long running resolve operation, then it would default to falling back to resolving bundles one at a time.

Thanks for all the insights, one question, does it help to provide more than one thread here?

> While we can surely document this. I don't want to give the impression that such things are API.

It would still be good I think to let people know it exist,s is not API and e.g. what are the default values.

**Comment by tjwatson** [comment] 2021-09-23 13:39
> 
> Thanks for all the insights, one question, does it help to provide more than one thread here?

That depends on if you have available cores on your system that can take the extra work.  If so then it can help speed up the work the resolver does because it will perform some of its algorithm in parallel.

> 
> It would still be good I think to let people know it exist,s is not API and e.g. what are the default values.

Sure, if you would like to open a bug we can remember to get some of the missing configuration properties documented.

**Comment by jukzi** [comment] 2022-08-10 10:39
JFR and VisualVM both show many samples near ResolverImpl.checkPackageSpaceConsistency() lines: 1442-1448
![image](https://user-images.githubusercontent.com/51790620/183881604-e0be8ef5-2589-4af7-a8e8-48a62a7e7205.png)

Thats basically a hash join but iterating over allImportRequirePkgs which is  often >>10 times bigger then pkgs.m_usedPkgs.
Especially if pkgs.m_usedPkgs is empty (happens) the construction of allImportRequirePkgs could be totally avoided.
![image](https://user-images.githubusercontent.com/51790620/183880319-0c523131-9169-4197-95f3-32fc966f2acb.png)
![image](https://user-images.githubusercontent.com/51790620/183880557-9d2bb8be-d281-4e2e-9dde-d555f116d8d9.png)
![image](https://user-images.githubusercontent.com/51790620/183881844-be1734d9-b33c-4826-85ce-8071f898aa49.png)

...

Do you want minor hints like this or only a solution to the NP problem?

**Comment by laeubi** [comment] 2022-08-10 10:43
@jukzi I think this is better placed here: https://github.com/eclipse-equinox/equinox/issues/93 tycho is jsut a consumer, and maybe even https://issues.apache.org/jira/browse/FELIX-5648 as Equinox is consuming this from Felix :-)
