### ISSUE TITLE
[compare-version-with-baselines] Improve logg outputs to be more precise

### ISSUE THREAD

**Issue by laeubi** [eclipse/tycho#943] opened 2022-05-06 03:59 UTC
We have situations where there is a strange "Expected to have bigger x.y.z than what is available in baseline" where for example the GH action fails:

https://github.com/eclipse-equinox/p2/runs/6291943623

while the CI build on jenkins suceeds.

@mickaelistria can you take a look at the logs what might causing this? I don't understand why there is a difference at all is this a bug in compare-version-with-baselines? Or in the jgit plugin? or configuration issue? Missing baseline replace? I remember that we have had a bug where we hacked the baseline replace a bit so maybe this bug do not work anymore here?
I'm also not sure what was the consents, if we said we want to rework the replace or ask maven to give us new API ...

**Comment by laeubi** [comment] 2022-05-06 04:12
I have triggered a fresh build

GH: https://github.com/eclipse-equinox/p2/actions/runs/2279668958
Jenkins: https://ci.eclipse.org/equinox/job/p2/job/master/132/

**Comment by laeubi** [comment] 2022-05-06 04:33
What I see at the GH action is an output that says:

> No baseline version MavenProject

and a warning:

> Warning:  artifact org.eclipse.equinox.p2:org.eclipse.equinox.frameworkadmin:xml:p2metadata:2.2.0-SNAPSHOT already attached, replace previous instance
> Warning:  artifact org.eclipse.equinox.p2:org.eclipse.equinox.frameworkadmin:xml:p2artifacts:2.2.0-SNAPSHOT already attached, replace previous instance

this seem to indicate that there are no baseline repositories ...

**Comment by laeubi** [comment] 2022-05-06 04:39
@akurtakov do you have an idea why the baseline repo is not picket up? I don't see how this could make a difference, is the Jenkins any sepcial env variables?

@mickaelistria I wonder if the log message (beside beeing not very informative) should better not be at warn level or even fail the build if any of these is enabled:
```
    /**
     * Fail the build if there are discrepancies between artifacts present both in build and
     * baseline. Attached artifacts only present in the build do not result in build failure.
     */
    failCommon,

    /**
     * Fail the build if there are any discrepancy between build and baseline artifacts.
     */
    fail;
```

having no baseline repos seems an error condition here I think.

**Comment by laeubi** [comment] 2022-05-06 04:42
Next thing: I think the default should be `disable` for the baseline mode, or we should treat `warn` as `disabled` when there are no baseline repos?
This most likeley produces useless outputs for user not using baselines...

**Comment by laeubi** [comment] 2022-05-06 04:45
I also like to remove the lock for this mojo it does not seem to need any global build lock here...

**Comment by akurtakov** [comment] 2022-05-06 06:53
Nothing special about baseline in Jenkinsfile AFAICT. Furthermore baseline check is skipped by default but you enable it explicitly by passing -Dcompare-version-with-baselines.skip=false  in maven.yml

**Comment by laeubi** [comment] 2022-05-06 06:56
> you enable it explicitly

That's what is used at the Jenkins CI as well, but I don't see any errors there about missing baseline repositories so I'm a bit confused here...

**Comment by laeubi** [comment] 2022-05-06 07:01
By the way I see the same problem with the swt build, disabling the check works but leaves a strange feeling as the Jenkins has exact same mvn command, so something seems to be missing here but I'm not familiar enough with this baseline stuff to tell what might be the root cause, I have prepared a change in Tycho now to hopefully get better error messages in case of missing repositories.

**Comment by mickaelistria** [comment] 2022-05-06 07:21
This is not a bug in compare-version-with-baselines, the error message is correct and baseline seems to be polled as expected.

Example error message
```
Failed to execute goal org.eclipse.tycho.extras:tycho-p2-extras-plugin:3.0.0-SNAPSHOT:compare-version-with-baselines (compare-attached-artifacts-with-release) on project org.eclipse.equinox.p2.ui.admin.rcp: Only qualifier changed for (org.eclipse.equinox.p2.ui.admin.rcp/1.3.200.v20220430-1901). Expected to have bigger x.y.z than what is available in baseline (1.3.200.v20211217-1131) -> [Help 1]
```

Earlier
```
 [INFO] --- tycho-packaging-plugin:3.0.0-SNAPSHOT:build-qualifier (default-build-qualifier) @ org.eclipse.equinox.p2.ui.admin.rcp ---
[INFO] The project's OSGi version is 1.3.200.v20220430-1901
```
says the OSGi version that is computed for this module.
And baseline comparison with snapshots ( https://download.eclipse.org/eclipse/updates/4.24-I-builds/I20220505-1800/ ) first says
```
No baseline version MavenProject: org.eclipse.equinox:org.eclipse.equinox.p2.ui.admin.rcp:1.3.200-SNAPSHOT @ /home/runner/work/p2/p2/bundles/org.eclipse.equinox.p2.ui.admin.rcp/pom.xml
```
because the OSGi version in baseline in 1.3.200.v20211217-1131 , so it cannot be used as a substitute (baseline replacement happens if same fully qualified versions are used as per https://wiki.eclipse.org/Tycho/Reproducible_Version_Qualifiers#What_does_this_actually_do.3F ), so 1.3.200.v20220430-1901 is kept and later comparison with release is right to complain that it's a qualifier-only change.

The issue that should be investigated in p2 build first is why a new qualifier is computed for these modules if there is no relevant change.

**Comment by laeubi** [comment] 2022-05-06 07:24
> No baseline version MavenProject

this is only issued if no baseline repository is defined. So how should it ever work then?

**Comment by mickaelistria** [comment] 2022-05-06 07:26
> this is only issued if no baseline repository is defined. 

Wrong. It's issued as well is 1. there is a baseline but 2. no fully qualified version of the bundle matches. This is part of tycho-p2-plugin.

**Comment by laeubi** [comment] 2022-05-06 07:31
> Wrong. It's issued as well is 1. there is a baseline but 2. no fully qualified version of the bundle matches. This is part of tycho-p2-plugin.

Okay I might get confused here then by the blocks, do you think we can came up with a better wording here? `No baseline version MavenProject xxx` does not really tell anything useful (to me) without investigate the code...

**Comment by laeubi** [comment] 2022-05-06 07:38
> Expected to have bigger x.y.z than what is available in baseline (1.3.200.v20211217-1131)

And is there any chance we can include in this message **why** `expected to have bigger x.y.z than what is available in baseline`? I can't get from the code what is the rationale of this ...

**Comment by laeubi** [comment] 2022-05-06 07:41
> The issue that should be investigated in p2 build first is why a new qualifier is computed for these modules if there is no relevant change.

But how? I see the same issue not only with p2 but swt as well... @HannesWell has reported this with m2e as well for some cases ...

**Comment by mickaelistria** [comment] 2022-05-06 07:42
It tells that there is no baseline version; it's actually correct. The issue is more that apparently it's prone to be over-interpreted despite being concise.
We could maybe log some more info to mojo execution, like
```
Checking baseline repo https://download.eclipse.org/eclipse/updates/4.24-I-builds ...
No baseline version for MavenProject: org.eclipse.equinox:org.eclipse.equinox.p2.ui.admin.rcp:1.3.200-SNAPSHOT @ /home/runner/work/p2/p2/bundles/org.eclipse.equinox.p2.ui.admin.rcp/pom.xml
```

> And is there any chance we can include in this message why expected to have bigger x.y.z than what is available in baseline?

It's a different baseline, a different goal, so no it can't be as part of the same mojo.
There is baseline comparison for replacement to reuse existing artifacts as much as possible, as part of tycho-p2-plugin.
And there is baseline comparison for verification against latest release, to verify versions have bumped as necessary and particularly to prevent from same x.y.z with different qualifiers. This is the goal of the compare-version-with-baselines mojo as documented in https://www.eclipse.org/tycho/sitedocs/tycho-extras/tycho-p2-extras-plugin/compare-version-with-baselines-mojo.html . Please also read https://wiki.eclipse.org/Tycho/Reproducible_Version_Qualifiers#What_does_this_actually_do.3F .
Then any suggestion to improve the message is welcome.

**Comment by laeubi** [comment] 2022-05-06 07:53
> It could be an issue with the move of jgit timestamp plugin that is messing up qualifier computation.

This error has happened long time before.

**Comment by mickaelistria** [comment] 2022-05-06 07:57
> This error has happened long time before.

Please provide examples. I believe that you're mixing several different errors, which in the very end show the same error, but looking up at the log tells the difference. This error can happen rightly, it's meant to be shown when necessary; it's normal to see it from time to time as a reminder that versions need to be bumped.

**Comment by laeubi** [comment] 2022-05-06 08:03
See https://github.com/eclipse-equinox/p2/actions/workflows/maven.yml?query=branch%3Amaster 

The earliest on I could find was 

https://github.com/eclipse-equinox/p2/runs/6048325585?check_suite_focus=true

**Comment by mickaelistria** [comment] 2022-05-06 08:07
> The earliest on I could find was https://github.com/eclipse-equinox/p2/runs/6048325585?check_suite_focus=true

That shows me a totally different and unrelated error.

**Comment by laeubi** [comment] 2022-05-06 08:09
Wrong link :-(

https://github.com/eclipse-equinox/p2/runs/6094773102?check_suite_focus=true

**Comment by laeubi** [comment] 2022-05-06 08:11
Also note that this is the master build, so rebase problems should not be an issue here right?

**Comment by mickaelistria** [comment] 2022-05-06 08:11
So it's happening only on GitHub actions? Only for some builds or only for some changes? ie can we have for the same change 1 successful and 1 failing build?

**Comment by laeubi** [comment] 2022-05-06 08:12
Only on GH and on all builds:

I have triggered a fresh build today:

GH: https://github.com/eclipse-equinox/p2/actions/runs/2279668958 --> fails (I have just disabled fae option here)
Jenkins: https://ci.eclipse.org/equinox/job/p2/job/master/132/ --> succeeds

**Comment by laeubi** [comment] 2022-05-06 08:15
Also here: https://github.com/eclipse-equinox/p2/pull/67#issuecomment-1119359008 only jenkinsfile was adjusted to enforce usage of another m2 repo to ensure nothing is cached:

Jenkins->Success
GH->Fails

**Comment by mickaelistria** [comment] 2022-05-06 08:40
Try adding `-X` for extra logging. The important part is `validate-version` which shouldn't give a recent date unless there is a recent change. It seems to be ignoring the git based qualifier.

**Comment by laeubi** [comment] 2022-05-06 08:49
I have now triggered a build with -X on GH and Jenkins, lets see if this shades some light on it.

**Comment by laeubi** [comment] 2022-05-06 08:58
Log output for GH can be found here: https://github.com/eclipse-equinox/p2/suites/6400173062/logs?attempt=1

**Comment by laeubi** [comment] 2022-05-06 09:49
Log for Ci with X option: https://ci.eclipse.org/equinox/job/p2/job/PR-67/3/consoleText

Any hints would be appreciated...

**Comment by mickaelistria** [comment] 2022-05-06 11:36
Good hint @HannesWell , it could indeed be that the checkout on GitHub actions is not complete enough to get history working well. The `--depth=1` in the fetch causes that; it can be reproduce via CLI that with `--depth=1` on fetch, then `git log` only contains latest commit and build computes qualifier from this commit for all contents instead of distinguishing modules. The GitHub workflow must be tweaked to keep history. That is true for all Eclipse projects using Tycho with jgit-timestamp-provider.
Let's close this as no further action is required on Tycho.

**Closed by mickaelistria** 2022-05-06 11:36 UTC

**Comment by laeubi** [comment] 2022-05-06 11:41
@HannesWell I think you are right. I wonder if we could somehow make the jgit still work with `--depth=1` as t is much more performant than check out the whole history. Maybe instead of using the local we can query remote history instead?

**Comment by HannesWell** [comment] 2022-05-06 12:03
That was not exactly what I meant, but nevertheless I'm glad my comment helped.

> @HannesWell I think you are right. I wonder if we could somehow make the jgit still work with `--depth=1` as t is much more performant than check out the whole history. Maybe instead of using the local we can query remote history instead?

It would be handy because then the workflows don't have to be adjusted, but it could be that the performance penalty is then just payed later.

**Comment by laeubi** [comment] 2022-05-06 13:20
@waynebeaton any chance we can make progress here? I have read some things where relaxed recently so maybe we can have something more useful here than two repos in different organizations?
