### ISSUE TITLE
Not a valid jar file!

### ISSUE THREAD

**Issue by minemeraj** [eclipse/tycho#1073] opened 2022-06-23 11:21 UTC
Hi,

Until last week the log looks like this:

```
[INFO] Performing subquery
[INFO] Resolving MavenDependencyRoots = [GroupId = de.dsa.eal, ArtifactId = de.dsa.core.features, Version = 0.0.1-SNAPSHOT, ArtifactType = jar, IncludeDependencyScope = , GroupId = de.dsa.eal, ArtifactId = de.dsa.rts.features, Version = 0.0.1-SNAPSHOT, ArtifactType = jar, IncludeDependencyScope = ], IncludeDependencyScope = [compile], MissingManifestStrategy = GENERATE, IncludeSource = true...
[WARNING] Invalid POM for de.dsa.eal.3pp:org.hsqldb:eclipse-plugin:2.6.1.20220516, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] Invalid POM for de.dsa.eal.3pp:org.apache.commons.jcs3:eclipse-plugin:3.0.0.20220504, transitive dependencies (if any) will not be available, enable debug logging for more details
```

But the build didn't fail!

But now it looks like:
```
[INFO] Performing subquery
[INFO] Resolving MavenDependencyRoots = [GroupId = de.dsa.eal, ArtifactId = de.dsa.core.features, Version = 0.0.1-SNAPSHOT, ArtifactType = jar, IncludeDependencyScope = , GroupId = de.dsa.eal, ArtifactId = de.dsa.rts.features, Version = 0.0.1-SNAPSHOT, ArtifactType = jar, IncludeDependencyScope = ], IncludeDependencyScope = [compile], MissingManifestStrategy = GENERATE, IncludeSource = true...
[WARNING] Invalid POM for de.dsa.eal.3pp:org.hsqldb:jar:2.6.1.20220516, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] Invalid POM for de.dsa.eal.3pp:org.apache.commons.jcs3:jar:3.0.0.20220504, transitive dependencies (if any) will not be available, enable debug logging for more details`


And the build failed with the message:

`[DEBUG] Resolved MavenArtifactFacade [wrappedArtifact=de.dsa.eal.3pp:org.hsqldb:jar:2.6.1.20220516:compile]...
[DEBUG] MavenResolver: artifact de.dsa.eal.3pp:org.hsqldb:2.6.1.20220516 at location /home/jenkins/workspace/workspace/WTS~e4_20/wts~03~e4_20_WTS/WTS/.m2/de/dsa/eal/3pp/org.hsqldb/2.6.1.20220516/org.hsqldb-2.6.1.20220516.jar resolves installable unit org.hsqldb/2.6.1.20220516
[DEBUG] Resolve de.dsa.eal.3pp:org.hsqldb:jar:sources:2.6.1.20220516...
[DEBUG] MavenResolver: source-artifact de.dsa.eal.3pp:org.hsqldb:2.6.1.20220516:sources at location /home/jenkins/workspace/workspace/WTS~e4_20/wts~03~e4_20_WTS/WTS/.m2/de/dsa/eal/3pp/org.hsqldb/2.6.1.20220516/org.hsqldb-2.6.1.20220516-sources.jar resolves installable unit org.hsqldb.source/2.6.1.20220516
[DEBUG] Resolved MavenArtifactFacade [wrappedArtifact=de.dsa.eal.3pp:org.hsqldb:jar:lib/hsqldb-2.6.1.jar:2.6.1.20220516:system]...
[DEBUG] Bundle Location:       /home/jenkins/workspace/workspace/WTS~e4_20/wts~01~e4_20_CORE/CORE/.m2/.cache/tycho/org.hsqldb-2.6.1.20220516.jar/lib/hsqldb-2.6.1.jar (Filesize 0)
[DEBUG] File isFile:           false
[ERROR] Failed to resolve target definition file:/home/jenkins/workspace/workspace/WTS~e4_20/wts~03~e4_20_WTS/WTS/dsa_target/eal-wts-target.target: Artifact MavenArtifactFacade [wrappedArtifact=de.dsa.eal.3pp:org.hsqldb:jar:lib/hsqldb-2.6.1.jar:2.6.1.20220516:system] of location MavenDependencyRoots = [GroupId = de.dsa.eal, ArtifactId = de.dsa.core.features, Version = 0.0.1-SNAPSHOT, ArtifactType = jar, IncludeDependencyScope = , GroupId = de.dsa.eal, ArtifactId = de.dsa.rts.features, Version = 0.0.1-SNAPSHOT, ArtifactType = jar, IncludeDependencyScope = ], IncludeDependencyScope = [compile], MissingManifestStrategy = GENERATE, IncludeSource = true is not a valid jar file -> [Help 1]
org.apache.maven.MavenExecutionException: Failed to resolve target definition file:/home/jenkins/workspace/workspace/WTS~e4_20/wts~03~e4_20_WTS/WTS/dsa_target/eal-wts-target.target: Artifact MavenArtifactFacade [wrappedArtifact=de.dsa.eal.3pp:org.hsqldb:jar:lib/hsqldb-2.6.1.jar:2.6.1.20220516:system] of location MavenDependencyRoots = [GroupId = de.dsa.eal, ArtifactId = de.dsa.core.features, Version = 0.0.1-SNAPSHOT, ArtifactType = jar, IncludeDependencyScope = , GroupId = de.dsa.eal, ArtifactId = de.dsa.rts.features, Version = 0.0.1-SNAPSHOT, ArtifactType = jar, IncludeDependencyScope = ], IncludeDependencyScope = [compile], MissingManifestStrategy = GENERATE, IncludeSource = true is not a valid jar file
    at org.eclipse.tycho.core.maven.TychoMavenLifecycleParticipant.afterProjectsRead (TychoMavenLifecycleParticipant.java:118)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:253)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
```

Which component has been changed since last week? No source code was changed just the log message changed and the build is failing. Any clue?

**Comment by laeubi** [comment] 2022-06-23 11:24
Please provide an [integration-test](https://github.com/eclipse/tycho/wiki#providing-an-integration-test) or example project to demonstrate the issue. It is quite impossible to guess from fragmented logoutput whats wrong here.

**Comment by laeubi** [comment] 2022-06-23 11:26
Might be a duplicate of #1072

**Comment by mickaelistria** [comment] 2022-06-27 15:12
@minemeraj Can you please try latest `3.0.0-SNAPSHOT` (pass `-U` to your maven command to force snapshot updates)? If @laeubi is right, then the issue should be already fixed.

**Comment by laeubi** [comment] 2022-07-10 06:03
Duplicate of #1072

**Closed by laeubi** 2022-07-10 06:03 UTC

**Comment by laeubi** [comment] 2023-01-05 13:17
> Is there any plan to backport the fix to 2.7.x so that it can work with Java 11?

Please see https://github.com/eclipse-tycho/tycho/blob/master/CONTRIBUTING.md#backporting regarding backports.

Beside that you can use Tycho3 to compile java11 code as well you just need java17 to run the build.

**Comment by azaylamba** [comment] 2023-01-05 13:28
Thanks for the quick reply. Just checked the jar file of version 2.7.5 and it seems the fix(https://github.com/eclipse-tycho/tycho/pull/1072/files) is already there.
However I am still getting the error "not a valid jar file" for some of the dependencies e.g. com.thoughtworks.paranamer_2.5.6

**Comment by laeubi** [comment] 2023-01-05 14:33
Probably the file is just broken, have you tried analyze/redownload/delete it?

**Comment by laeubi** [comment] 2023-01-06 11:17
If I understand correctly you are using this artifact:
https://mvnrepository.com/artifact/javax.inject/javax.inject/1

this is not a jar file, it is a plain zip named jar as it is missing a manifest and that's why Tycho complains here.

**Comment by azaylamba** [comment] 2023-01-06 11:56
I am not directly using this artifact. This is an optional dependency of https://mvnrepository.com/artifact/com.thoughtworks.paranamer/paranamer/2.5.6 and it is being fetched automatically during the build.

**Comment by azaylamba** [comment] 2023-01-06 12:10
Ok thanks. I am new to contributing so it might take some time. Will try to provide the integration test over the weekend.
