### ISSUE TITLE
Tycho-extra p2-metadata fails with maven 3.8.2

### ISSUE THREAD

**Issue by sbouchet** [eclipse/tycho#298] opened 2021-09-21 09:34 UTC
hi,

with the recent update of the GitHub images, moving Maven version from 3.8.1 to 3.8.2, my build started to fails with an UnsupportedOperationException error.

Below the piece of code that worked in 3.8.1 :  
```
[INFO] --- tycho-source-plugin:2.2.0:plugin-source (plugin-source) @ com.jboss.devstudio.core.cheatsheets ---
[INFO] Building jar: /home/sbouchet/git/jbdevstudio-product/plugins/com.jboss.devstudio.core.cheatsheets/target/com.jboss.devstudio.core.cheatsheets-12.21.0-SNAPSHOT-sources.jar
[INFO] 
[INFO] --- target-platform-configuration:2.2.0:target-platform (default-target-platform) @ com.jboss.devstudio.core.cheatsheets ---
[INFO] 
[INFO] --- tycho-packaging-plugin:2.2.0:package-plugin (default-package-plugin) @ com.jboss.devstudio.core.cheatsheets ---
[INFO] Building jar: /home/sbouchet/git/jbdevstudio-product/plugins/com.jboss.devstudio.core.cheatsheets/target/com.jboss.devstudio.core.cheatsheets-12.21.0-SNAPSHOT.jar
[INFO] 
[INFO] --- tycho-p2-plugin:2.2.0:p2-metadata-default (default-p2-metadata-default) @ com.jboss.devstudio.core.cheatsheets ---
[WARNING] MavenProject: com.jboss.devstudio.core.plugins:com.jboss.devstudio.core.cheatsheets:12.21.0-SNAPSHOT @ /home/sbouchet/git/jbdevstudio-product/plugins/com.jboss.devstudio.core.cheatsheets/pom.xml: baseline and build artifacts have same version but different contents
   classifier-sources: not present in baseline

[INFO] MavenProject: com.jboss.devstudio.core.plugins:com.jboss.devstudio.core.cheatsheets:12.21.0-SNAPSHOT @ /home/sbouchet/git/jbdevstudio-product/plugins/com.jboss.devstudio.core.cheatsheets/pom.xml
    The main artifact has been replaced with the baseline version.
    The following attached artifacts are not present in the baseline and have been removed: [sources]

[INFO] 
[INFO] --- tycho-source-plugin:2.2.0:feature-source (feature-source) @ com.jboss.devstudio.core.cheatsheets ---
[INFO] 
[INFO] --- repository-utils:2.2.0:generate-repository-facade (generate-facade) @ com.jboss.devstudio.core.cheatsheets ---
[INFO] 
[INFO] --- tycho-p2-plugin:2.2.0:p2-metadata (attached-p2-metadata) @ com.jboss.devstudio.core.cheatsheets ---
[INFO] MavenProject: com.jboss.devstudio.core.plugins:com.jboss.devstudio.core.cheatsheets:12.21.0-SNAPSHOT @ /home/sbouchet/git/jbdevstudio-product/plugins/com.jboss.devstudio.core.cheatsheets/pom.xml
    The main artifact has been replaced with the baseline version.

[INFO] 
[INFO] -----------------< com.jboss.devstudio.core:features >------------------
```

and now using 3.8.2 
```
[INFO] --- tycho-source-plugin:2.2.0:plugin-source (plugin-source) @ com.jboss.devstudio.core.cheatsheets ---
[INFO] Building jar: /home/sbouchet/git/jbdevstudio-product/plugins/com.jboss.devstudio.core.cheatsheets/target/com.jboss.devstudio.core.cheatsheets-12.21.0-SNAPSHOT-sources.jar
[INFO] 
[INFO] --- target-platform-configuration:2.2.0:target-platform (default-target-platform) @ com.jboss.devstudio.core.cheatsheets ---
[INFO] 
[INFO] --- tycho-packaging-plugin:2.2.0:package-plugin (default-package-plugin) @ com.jboss.devstudio.core.cheatsheets ---
[INFO] Building jar: /home/sbouchet/git/jbdevstudio-product/plugins/com.jboss.devstudio.core.cheatsheets/target/com.jboss.devstudio.core.cheatsheets-12.21.0-SNAPSHOT.jar
[INFO] 
[INFO] --- tycho-p2-plugin:2.2.0:p2-metadata-default (default-p2-metadata-default) @ com.jboss.devstudio.core.cheatsheets ---
[WARNING] MavenProject: com.jboss.devstudio.core.plugins:com.jboss.devstudio.core.cheatsheets:12.21.0-SNAPSHOT @ /home/sbouchet/git/jbdevstudio-product/plugins/com.jboss.devstudio.core.cheatsheets/pom.xml: baseline and build artifacts have same version but different contents
   classifier-sources: not present in baseline

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for devstudio - Product, Installers 12.21.0-SNAPSHOT:
[INFO] 
[INFO] devstudio - Product, Installers .................... SUCCESS [  0.364 s]
[INFO] devstudio - Product Plugins - Core ................. SUCCESS [  0.020 s]
[INFO] com.jboss.devstudio.core ........................... SUCCESS [ 18.213 s]
[INFO] com.jboss.devstudio.core.project.examples .......... SUCCESS [  2.811 s]
[INFO] com.jboss.devstudio.core.usage.branding ............ SUCCESS [  3.341 s]
[INFO] com.jboss.devstudio.core.central ................... SUCCESS [  1.098 s]
[INFO] com.jboss.devstudio.core.capabilities .............. SUCCESS [  2.668 s]
[INFO] com.jboss.devstudio.core.cheatsheets ............... FAILURE [  0.762 s]
[INFO] devstudio - Product Features - Core ................ SKIPPED
[INFO] com.jboss.devstudio.core.feature ................... SKIPPED
[INFO] com.jboss.devstudio.core.feature.source ............ SKIPPED
[INFO] com.jboss.devstudio.core.capabilities.feature ...... SKIPPED
[INFO] com.jboss.devstudio.core.capabilities.feature.source SKIPPED
[INFO] com.jboss.devstudio.fuse.feature ................... SKIPPED
[INFO] com.jboss.devstudio.core.site ...................... SKIPPED
[INFO] p2-director ........................................ SKIPPED
[INFO] com.jboss.devstudio.core.p2.director ............... SKIPPED
[INFO] p2-director ........................................ SKIPPED
[INFO] installer .......................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  50.754 s
[INFO] Finished at: 2021-09-21T11:23:18+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-p2-plugin:2.2.0:p2-metadata-default (default-p2-metadata-default) on project com.jboss.devstudio.core.cheatsheets: Execution default-p2-metadata-default of goal org.eclipse.tycho:tycho-p2-plugin:2.2.0:p2-metadata-default failed.: UnsupportedOperationException -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :com.jboss.devstudio.core.cheatsheets

2021-09-21T08:53:06.7784888Z [ERROR] Failed to execute goal org.eclipse.tycho:tycho-p2-plugin:2.4.0:p2-metadata-default (default-p2-metadata-default) on project com.jboss.devstudio.core.cheatsheets: Execution default-p2-metadata-default of goal org.eclipse.tycho:tycho-p2-plugin:2.4.0:p2-metadata-default failed.: UnsupportedOperationException -> [Help 1]
2021-09-21T08:53:06.7789558Z org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.eclipse.tycho:tycho-p2-plugin:2.4.0:p2-metadata-default (default-p2-metadata-default) on project com.jboss.devstudio.core.cheatsheets: Execution default-p2-metadata-default of goal org.eclipse.tycho:tycho-p2-plugin:2.4.0:p2-metadata-default failed.
2021-09-21T08:53:06.7793035Z     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
2021-09-21T08:53:06.7795027Z     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
2021-09-21T08:53:06.7797028Z     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
2021-09-21T08:53:06.7799554Z     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
2021-09-21T08:53:06.7802663Z     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
2021-09-21T08:53:06.7806391Z     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
2021-09-21T08:53:06.7809677Z     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
2021-09-21T08:53:06.7811497Z     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
2021-09-21T08:53:06.7812812Z     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
2021-09-21T08:53:06.7814076Z     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
2021-09-21T08:53:06.7815279Z     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:972)
2021-09-21T08:53:06.7816407Z     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
2021-09-21T08:53:06.7817470Z     at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
2021-09-21T08:53:06.7818891Z     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
2021-09-21T08:53:06.7820859Z     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
2021-09-21T08:53:06.7823195Z     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
2021-09-21T08:53:06.7824932Z     at java.lang.reflect.Method.invoke (Method.java:566)
2021-09-21T08:53:06.7826541Z     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
2021-09-21T08:53:06.7828679Z     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
2021-09-21T08:53:06.7831294Z     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
2021-09-21T08:53:06.7833608Z     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
2021-09-21T08:53:06.7836324Z Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-p2-metadata-default of goal org.eclipse.tycho:tycho-p2-plugin:2.4.0:p2-metadata-default failed.
2021-09-21T08:53:06.7838965Z     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:148)
2021-09-21T08:53:06.7841309Z     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
2021-09-21T08:53:06.7843322Z     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
2021-09-21T08:53:06.7845308Z     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
2021-09-21T08:53:06.7847862Z     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
2021-09-21T08:53:06.7851004Z     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
2021-09-21T08:53:06.7854532Z     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
2021-09-21T08:53:06.7857735Z     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
2021-09-21T08:53:06.7859552Z     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
2021-09-21T08:53:06.7860864Z     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
2021-09-21T08:53:06.7862155Z     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
2021-09-21T08:53:06.7863350Z     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:972)
2021-09-21T08:53:06.7864490Z     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
2021-09-21T08:53:06.7865559Z     at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
2021-09-21T08:53:06.7866976Z     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
2021-09-21T08:53:06.7868968Z     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
2021-09-21T08:53:06.7871415Z     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
2021-09-21T08:53:06.7873177Z     at java.lang.reflect.Method.invoke (Method.java:566)
2021-09-21T08:53:06.7874981Z     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
2021-09-21T08:53:06.7877198Z     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
2021-09-21T08:53:06.7879397Z     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
2021-09-21T08:53:06.7881541Z     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
2021-09-21T08:53:06.7883042Z Caused by: java.lang.UnsupportedOperationException
2021-09-21T08:53:06.7884134Z     at java.util.Collections$UnmodifiableList$1.remove (Collections.java:1350)
2021-09-21T08:53:06.7885896Z     at org.eclipse.tycho.plugins.p2.BaselineValidator.validateAndReplace (BaselineValidator.java:149)
2021-09-21T08:53:06.7888302Z     at org.eclipse.tycho.plugins.p2.P2MetadataMojo.attachP2Metadata (P2MetadataMojo.java:186)
2021-09-21T08:53:06.7890303Z     at org.eclipse.tycho.plugins.p2.P2MetadataMojo.execute (P2MetadataMojo.java:140)
2021-09-21T08:53:06.7892930Z     at org.eclipse.tycho.plugins.p2.P2MetadataDefaultMojo.execute (P2MetadataDefaultMojo.java:34)
2021-09-21T08:53:06.7895430Z     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
2021-09-21T08:53:06.7897807Z     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
2021-09-21T08:53:06.7899825Z     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
2021-09-21T08:53:06.7901827Z     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
2021-09-21T08:53:06.7904359Z     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
2021-09-21T08:53:06.7907469Z     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
2021-09-21T08:53:06.7912128Z     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
2021-09-21T08:53:06.7915391Z     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
2021-09-21T08:53:06.7917225Z     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
2021-09-21T08:53:06.7918525Z     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
2021-09-21T08:53:06.7919803Z     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
2021-09-21T08:53:06.7921013Z     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:972)
2021-09-21T08:53:06.7922127Z     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
2021-09-21T08:53:06.7923202Z     at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
2021-09-21T08:53:06.7924610Z     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
2021-09-21T08:53:06.7926582Z     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
2021-09-21T08:53:06.7928916Z     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
2021-09-21T08:53:06.7930646Z     at java.lang.reflect.Method.invoke (Method.java:566)
2021-09-21T08:53:06.7933283Z     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
2021-09-21T08:53:06.7935440Z     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
2021-09-21T08:53:06.7937846Z     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
2021-09-21T08:53:06.7939997Z     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
```

note that: 
- I can reproduce locally
- I tested with latest tycho 2.4.0 too and same error
- my code shows some baseline info that seems to be the cause of the exception ( The following attached artifacts are not present in the baseline and have been removed: [sources] )
- if I use the -DbaselineCompareReplace=common flag, the build passes.

**Comment by akurtakov** [comment] 2021-09-21 09:37
Does it happen with 2.4.0 or 2.5.0-SNAPSHOTS?

**Comment by akurtakov** [comment] 2021-09-21 09:39
Can you point us to reproducer?

**Comment by akurtakov** [comment] 2021-09-21 09:41
Also can you try with 2.5.0-SNAPSHOT as per #295 ?

**Comment by laeubi** [comment] 2021-09-21 09:42
See https://github.com/eclipse/tycho/issues/261

**Comment by sbouchet** [comment] 2021-09-21 12:34
@akurtakov : reproducer is https://github.com/jbdevstudio/jbdevstudio-product/pull/577
currently using tycho 2.2.0 but locally I'm able to reproduce using 2.4.0 with -DtychoVersion=2.4.0
will try 2.5.0-SNAPSHOT

**Comment by sbouchet** [comment] 2021-09-21 12:53
as expected it also fails with 2.5.0-SNAPSHOT 
```
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-p2-plugin:2.5.0-SNAPSHOT:p2-metadata-default (default-p2-metadata-default) on project com.jboss.devstudio.core.cheatsheets: Execution default-p2-metadata-default of goal org.eclipse.tycho:tycho-p2-plugin:2.5.0-SNAPSHOT:p2-metadata-default failed.: UnsupportedOperationException -> [Help 1]
[ERROR] 
```

**Comment by mickaelistria** [comment] 2021-09-21 16:13
Closing as duplicate of #261

**Closed by mickaelistria** 2021-09-21 16:13 UTC

**Comment by laeubi** [comment] 2021-09-22 04:29
@sbouchet do you think you can derive a minimal test case for this?

**Comment by laeubi** [comment] 2021-09-22 05:06
> reproducer is [jbdevstudio/jbdevstudio-product#577](https://github.com/jbdevstudio/jbdevstudio-product/pull/577)

Where do I get maven-settings.xml ? It also seems to require a setting of `${jbosstools-site}`

**Comment by sbouchet** [comment] 2021-09-22 06:12
if you look at the github action that runs the build, we use it from jbosstools/jbosstools-build-ci repo.

**Comment by sbouchet** [comment] 2021-09-22 06:13
i'm not sure i can set a minimal test case, but it fails pretty fast

**Comment by laeubi** [comment] 2021-09-22 06:36
I also get the failure, but the more important point is that we get an integration-test in tycho that now fails so we can

1. make sure a fix solves the problem
2. it does not happen again in the future
