### ISSUE TITLE
tycho-compiler-plugin validate-classpath fails if two plugin dependencies depend on different versions of gson themselves

### ISSUE THREAD

**Issue by sebthom** [eclipse/tycho#1103] opened 2022-07-01 22:19 UTC
I am developing an eclipse plugin that has dependencies to Eclipse TM4E and Eclipse LSP4E. TM4E released a new version some days ago which now requires gson 2.9.0 instead of 2.8.9 as before. My tycho builds which worked fine for the last year now fail with:

```python
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:2.7.3:validate-classpath (default-validate-classpath) 
on project test.plugin: Execution default-validate-classpath of goal org.eclipse.tycho:tycho-compiler-plugin:2.7.3:validate-classpath failed:
org.osgi.framework.BundleException: Bundle test.plugin cannot be resolved:test.plugin [134]
[ERROR]   Unresolved requirement: Require-Bundle: org.eclipse.lsp4e
[ERROR]     -> Bundle-SymbolicName: org.eclipse.lsp4e; bundle-version="0.13.12.202206011407"; singleton:="true"
[ERROR]        org.eclipse.lsp4e [102]
[ERROR]          Unresolved requirement: Require-Bundle: org.eclipse.lsp4j.jsonrpc; bundle-version="[0.14.0,0.15.0)"
[ERROR]            -> Bundle-SymbolicName: org.eclipse.lsp4j.jsonrpc; bundle-version="0.14.0.v20220526-1518"
[ERROR]               org.eclipse.lsp4j.jsonrpc [106]
[ERROR]                 Unresolved requirement: Import-Package: com.google.gson; version="[2.8.9,2.9.0)"
[ERROR]          Unresolved requirement: Require-Bundle: org.eclipse.lsp4j; bundle-version="[0.14.0,0.15.0)"
[ERROR]            -> Bundle-SymbolicName: org.eclipse.lsp4j; bundle-version="0.14.0.v20220526-1518"
[ERROR]               org.eclipse.lsp4j [105]
[ERROR]                 Unresolved requirement: Import-Package: com.google.gson; version="[2.8.9,2.9.0)"
```

Apparently LSP4E depends on LSP4J which basically pinned it's gson dependency version to 2.8.9.
Since OSGI supports plugins depending on different versions of another plugin it should actually not an issue if LSP4E/LSP4J requires gson 2.8.9 and TM4E requires gson 2.9.0.

Interestingly trying to install TM4E and LSP4E/LSP4J manually into a barebone Eclipse Platform https://download.eclipse.org/eclipse/downloads/drops4/R-4.24-202206070700/download.php?dropFile=eclipse-platform-4.24-win32-x86_64.zip or any other Eclipse distribution works without any conflicts.

Also I can still build and directly run my plugin via a launch configuration from within Eclipse IDE, so I only experience the issue with tycho.

I created a minimal test Maven project to reproduce the issue [test.zip](https://github.com/eclipse/tycho/files/9031847/test.zip). Just run `mvn package` using a Java 17 JDK and the error will appear.

If you remove the dependency to TM4E from the META-INF/MANIFEST.MF the build succeeds. Which proves that the gson 2.8.9 is resolvable/discoverable via the given platform target configuration (see the included build.target file).

Any thoughts/suggestions/explanations are highly appreciated.

**Comment by sebthom** [comment] 2022-07-01 22:19
@martinlippert This issue might be interesting for you too.

**Comment by sebthom** [comment] 2022-07-08 17:47
@mickaelistria any thoughts on this?

**Comment by laeubi** [comment] 2022-07-08 17:55
I can only suggest to not "require-bundle" your dependencies, this normally relaxes the choices for the resolver a lot.

Nerveless I wonder if it is really required to have such a narrow version range here.

**Comment by laeubi** [comment] 2022-07-08 18:02
By the way I think the problem here is that P2 only choose *one* of the gsons (and not two) so either of those is missing. SO if you install this into eclipse, and install them separately, both bundles will be installed and there is no problem, but here one tries to install all at once and that fails.

**Comment by sebthom** [comment] 2022-07-08 18:15
Both update sites declared in the target definitions provide the required gson versions:
TM4E: https://download.eclipse.org/tm4e/releases/latest/plugins/com.google.gson_2.9.0.jar
LSP4E: https://download.eclipse.org/lsp4e/releases/latest/plugins/com.google.gson_2.8.9.v20220111-1409.jar
Is there a way to see why the 2.8.9 version is not found by P2?

**Comment by mickaelistria** [comment] 2022-07-08 20:31
You may try to just add a requirement to com.google.gson 2.9.0 in your bundle pom. This may force inclusion of this newer version and let the compiler find it.

**Comment by sebthom** [comment] 2022-07-08 20:36
> You may try to just add a requirement to com.google.gson 2.9.0 in your bundle pom. This may force inclusion of this newer version and let the compiler find it.

My bundle does not require gson at all, only depends on LSP4E and TM4E. Anyways, I tried your suggestion to add a requirement for gson 2.90 to my bundle and also tried to set a requirement for gson 2.8.9. Makes no difference, the build fails with the same error complaining LSP4E->LSP4J->GSON 2.8.9 unresolved requirement.

**Comment by laeubi** [comment] 2022-07-09 04:12
> Is there a way to see why the 2.8.9 version is not found by P2?

I don't say it is not found by P2 but P2 might only choose one of booth. Still the question remains why lsp4x has such a narrow version requirement to gson that makes it incompatible with even minor version changes.

**Comment by mickaelistria** [comment] 2022-07-09 09:32
p2 is not to blame here. p2 does include both version of gson in the target-platform resolution for this bundle. Both `mvn dependency:list` and a breakpoint in `OsgiBundleProject.resolveClassPath` looking into `dependencyArtifacts` show that they are available.
The issue happens really in OSGi resolution; as the issue doesn't exist in usual IDE, I suspect there can be a bug in how the OSGi dependency resolution is implemented in Tycho.

**Comment by laeubi** [comment] 2022-07-09 10:01
If it is really the case that one required `com.google.gson; version="[2.8.9,2.9.0)"` and the other require `com.google.gson; version="[2.9.0,3.0.0)"` then this is just not resolvable.... so I suspect that either the problem description is incomplete or in the IDE other providers are choosen.
What about not using require-bundle but import packages, as these allow more freedom to the resolver...

**Comment by laeubi** [comment] 2022-07-09 10:12
By the way this might be a rare case where uses clauses be relevant so `-Dtycho.equinox.resolver.uses=true` could be tried, but be aware that this increases resolvetime considerable and might fail in some cases as P2 do not understand use-contraints.

**Comment by sebthom** [comment] 2022-07-09 10:53
> If it is really the case that one required `com.google.gson; version="[2.8.9,2.9.0)"` and the other require `com.google.gson; version="[2.9.0,3.0.0)"` then this is just not resolvable....
My understanding of how dependency resolution works in OSGI etc. is very limited. Are you saying that when one bundle depends on two other bundles (TM4E,LSP4E) which themselves have transitive dependencies to mutually exclusive version ranges of the same bundle (gson) than this is an unresolvable situation? My understanding was the whole idea of OSGI's usage of isolated classloaders was that bundles can depend on different versions of other bundles at the same time (which e.g. is in contrast to Maven dependency resolution).

**Comment by laeubi** [comment] 2022-07-09 11:11
> usage of isolated classloaders was that **bundles** can depend on **different versions**

Emphasis by me, OSGi needs to build a consistent classspace for each bundle, so **different** bundles can depend on **different** versions, but one bundle can't depend on multiple versions at the same time, with require-bundle you essentially force one class-space as the intersection of all dependencies. So if the version ranges are really that narrow, you ask for a class-space for your bundle that contains the same package in different versions, what is forbidden.

That's why I wrote using import package and more wider version ranges might make this satisfiable.

> is in contrast to Maven dependency resolution

different modules can have different dependencies without a problem.

**Comment by sebthom** [comment] 2022-07-09 11:39
@laeubi thanks for the explanation! So I now tried to replace `Require-Bundle` with `Import-Package`, but unfortunately the build still fails:

Old:
```python
Require-Bundle: org.eclipse.platform;bundle-version="4.22.0",
 org.eclipse.lsp4j,
 org.eclipse.tm4e.core
```
New:
```python
Require-Bundle: org.eclipse.platform;bundle-version="4.22.0"
Import-Package: org.eclipse.lsp4j,
 org.eclipse.tm4e.core
```

Error:
```
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:2.7.3:validate-classpath (default-validate-classpath) on project test.plugin: Execution default-validate-classpath of goal org.eclipse.tycho:tycho-compiler-plugin:2.7.3:validate-classpath failed: org.osgi.framework.BundleException: Bundle test.plugin cannot be resolved:test.plugin [91]
[ERROR]   Unresolved requirement: Import-Package: org.eclipse.lsp4j
[ERROR]     -> Export-Package: org.eclipse.lsp4j; bundle-symbolic-name="org.eclipse.lsp4j"; bundle-version="0.14.0.v20220526-1518"; version="0.14.0.v20220526-1518"
[ERROR]        org.eclipse.lsp4j [74]
[ERROR]          Unresolved requirement: Import-Package: com.google.gson; version="[2.8.9,2.9.0)"
```

For comparison here are the reproducers:
[test-import-package.zip](https://github.com/eclipse/tycho/files/9076404/test-import-package.zip)
[test-require-bundle.zip](https://github.com/eclipse/tycho/files/9076405/test-require-bundle.zip)

**Comment by laeubi** [comment] 2022-07-09 11:46
> The issue happens really in OSGi resolution;

Has you checked that both are included in the created resolver state?

**Comment by mickaelistria** [comment] 2022-07-09 13:00
> so different bundles can depend on different versions, but one bundle can't depend on multiple versions at the same time

It's not the case here. AFAIK, TM4E doesn't re-export the GSon 2.9.0 packages, so the dependency is non-transitive and it should be legal for a bundle that consumes TM4E to Import-Package totally independently of what TM4E is using.

> Has you checked that both are included in the created resolver state?

Yes. They are both included in the state.

**Comment by laeubi** [comment] 2022-07-09 17:55
> It's not the case here. AFAIK, TM4E doesn't re-export the GSon 2.9.0 packages, so the dependency is non-transitive and it should be legal for a bundle that consumes TM4E to Import-Package totally independently of what TM4E is using.

It depends, this is only valid if TM4E uses GSon completely internally and do not export any of its API e.g as a return value or parameter or annotations I haven't checked yet TM4Es code if that might be the case somewhere.

> So I now tried to replace `Require-Bundle` with `Import-Package`, but unfortunately the build still fails

The import-package example runs successful for me using:

`mvn clean install -Dtycho.equinox.resolver.uses=true`

**Comment by laeubi** [comment] 2022-07-14 17:19
Close, as it works as intended here, please let us know if there are any issue left.

**Comment by mickaelistria** [comment] 2022-07-26 08:48
I'm reopening as this does not work as intended. It's intended that Tycho works just like OSGi and doesn't fail in cases where Equinox succeeds.

> I haven't checked yet TM4Es code if that might be the case somewhere.

I just checked and believe it's not the case.

> `mvn clean install -Dtycho.equinox.resolver.uses=true`

So it `tycho.equinox.resolver.uses=true` makes Tycho just work normally just like Equinox, shouldn't this be the default?

**Comment by laeubi** [comment] 2022-07-26 08:53
> I'm reopening as this does not work as intended.

This works as intended ...

> It's intended that Tycho works just like OSGi and doesn't fail in cases where Equinox succeeds.

Tycho succeeds here if you enable full use-clause processing, what only is necessary because of obscure requirement configurations of closely related projects.

> So it `tycho.equinox.resolver.uses=true` makes Tycho just work normally just like Equinox, shouldn't this be the default?

No as it is not necessary for most use-cases and is ultra slow in some not so cases or even can fail completely as Tycho is **not** requiring a consistent (runtime) class-space, it only needs to find out the exposed packages for compilation.

**Comment by laeubi** [comment] 2022-07-26 08:57
Please also see where it causes issues at runtime:
- https://github.com/eclipse-equinox/equinox/issues/84#issuecomment-1191295997

**Comment by mickaelistria** [comment] 2022-07-26 08:58
> This works as intended ...

That's now how I intend Tycho to work. Tycho should not create at built-time issues that are not happening at runtime.

> Tycho succeeds here if you enable full use-clause processing, what only is necessary because of obscure requirement configurations of closely related projects.

Yet, Equinox does work fine with those "obscure requirement configurations of closely related projects", Tycho should too.

> is ultra slow in some not so cases or even can fail completely as Tycho is not requiring a consistent (runtime) class-space, it only needs to find out the exposed packages for compilation.

Those cases are also slow in plain Equinox, aren't they? It makes sense to align default Tycho behavior with Equinox one here to not give the impression Tycho creates new issues over plain Equinox. Consistency actually reduces the amount of issues.

**Comment by mickaelistria** [comment] 2022-07-26 09:01
I believe that enabling `uses` + giving a 10seconds timeout would make this case work, and be more consistent with Equinox while hopefully not be harmful to the vast majority of other projects (would it?)

**Comment by laeubi** [comment] 2022-07-26 09:07
> That's now how I intend Tycho to work. Tycho should not create at built-time issues that are not happening at runtime.

Well this was **explicitly** added as a feature to prevent people from waiting **hours** to complete their builds. So one has always balance things.

> Yet, Equinox does work fine

It does not work "fine" it works fine for this singular case, in other cases it just runs "forever" (in terms of the user-time)

> Those cases are also slow in plain Equinox, aren't they? It makes sense to align default Tycho behavior with Equinox one here to not give the impression Tycho creates new issues over plain Equinox. 

They are not necessarily that slow in a "real" runtime, because for example you not install that much and do not install conflicting things, and as explained Tycho actually don't need nor require a consistent *runtime* class space but only needs to know for a compile class space what packages a given module is exposed to what is a much much simpler requirement (that could be solved in polynomial time) while a [SAT](https://en.wikipedia.org/wiki/Boolean_satisfiability_problem) what is a [NP-complete](https://en.wikipedia.org/wiki/NP-completeness) problem.

> Consistency actually reduces the amount of issues.

This is the only issue for a long time, and it is cause by super-narrow version ranges while still exposing them in the API somewhere giving the resolver a hard time. So if one want to simply ignore OSGi-best-practice its fine for me and threre is a commandline switch for those who don't mind working many hours for their build to complete, the rest really appreciate the much faster build times.

**Comment by laeubi** [comment] 2022-07-26 09:10
> I believe that enabling `uses` + giving a 10seconds timeout would make this case work, and be more consistent with Equinox while hopefully not be harmful to the vast majority of other projects (would it?)

I often build projects > 300 modules, and there where even reports for > 1000 modules so even ten seconds will increase build times considerably.

**Comment by mickaelistria** [comment] 2022-07-26 09:20
> I often build projects > 300 modules, and there where even reports for > 1000 modules so even ten seconds will increase build times considerably.

Are all the 300 modules affected by the fact that `uses` would add 10+ extra second each?

**Comment by laeubi** [comment] 2022-07-26 09:41
> Are all the 300 modules affected by the fact that `uses` would add 10+ extra second each?

One could not know as it depends on how projects relate to each other, what is in the target and so on, there where some experiment to find "good defaults" and it was found that the current ones (disabling use-clause processing) are both fast and not to cause no issue for a broad audience.

So I'm really not convinced to start this discussion again for academic purpose just because LSP4x refuse to manage their dependencies in a consumer friendly way and slow down all others if there is a switch available for those rare cases.

**Comment by mickaelistria** [comment] 2022-07-26 09:50
Would it be do-able that in such case of a dependency resolution issue, then another attempt is made with the "normal" resolver behavior (eg `uses=true`) ?

**Comment by laeubi** [comment] 2022-07-26 10:03
> Would it be do-able that in such case of a dependency resolution issue, then another attempt is made with the "normal" resolver behavior (eg `uses=true`) ?

Sure why not, I just rember there where cases where it runs very long (several minutes) so one should at least writeout a log message like: "Initial resolving failed, trying harder now ... " so the user is aware of something heavy and possibly long running is going on...

**Comment by mickaelistria** [comment] 2022-07-26 21:50
Submitted PR https://github.com/eclipse/tycho/pull/1201

**Closed** 2022-07-27 12:13 UTC
