### ISSUE TITLE
tycho-source-plugin:feature-source is not equivalent to tycho-source-feature-plugin:source-feature

### ISSUE THREAD

**Issue by estepper** [eclipse/tycho#524] opened 2022-01-09 14:13 UTC
I noticed that my Tycho build warns me that tycho-source-feature-plugin:source-feature is depracated and that "tycho-source-plugin:feature-source is eqivalent and even enhanced".

Can't judge if it's enhanced, but it's not equivalent!
I updated my poms accordingly and now I get this:

[ERROR] Cannot resolve project dependencies:
[ERROR]   Software being installed: org.eclipse.emf.cdo.releng.site raw:1.0.0.'SNAPSHOT'/format(n[.n=0;[.n=0;[-S]]]):1.0.0-SNAPSHOT
[ERROR]   Missing requirement: org.eclipse.emf.cdo.releng.site raw:1.0.0.'SNAPSHOT'/format(n[.n=0;[.n=0;[-S]]]):1.0.0-SNAPSHOT requires 'org.eclipse.equinox.p2.iu; org.eclipse.emf.cdo.all.source.feature.group 0.0.0' but it could not be found
[ERROR] 
[ERROR] See https://wiki.eclipse.org/Tycho/Dependency_Resolution_Troubleshooting for help.
[ERROR] Cannot resolve dependencies of MavenProject: org.eclipse.emf.cdo.features:org.eclipse.emf.cdo.releng.site:1.0.0-SNAPSHOT @ C:\develop\cdo-master\git\cdo\releng\org.eclipse.emf.cdo.releng.site\pom.xml: See log for details -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MavenExecutionException

**Comment by laeubi** [comment] 2022-01-09 15:55
Duplicate of #85

**Comment by laeubi** [comment] 2022-01-09 15:56
@estepper please check if https://github.com/eclipse/tycho/issues/85#issuecomment-824774937 solves your problem.

**Closed by laeubi** 2022-01-09 15:55 UTC

**Comment by estepper** [comment] 2022-01-10 03:16
Hi Christoph,
Thanks for the quick reply. And yes, #85 fixed my problem!
Let me repeat what Andreas said: Not in a million years I would have thought this to be the cause :P
