### ISSUE TITLE
Support for Java 16

### ISSUE THREAD

**Issue by LorenzoBettini** [eclipse/tycho#136] opened 2021-05-21 12:35 UTC
Hi, when trying to use Tycho 2.3.0 with a project where the compilation level is set to 16 I get the following error:

```Fatal error compiling: target level should be in '1.1'...'1.8','9'...'15' (or '5.0'..'15.0') or cldc1.1: 16```

is support for Java 16 planned for 2.4.0?

I tried to search for the current issues also in Bugzilla but did not find anything...

**Comment by akurtakov** [comment] 2021-05-21 12:49
There is no released version of ecj supporting target 16. Once it's released in end of June Tycho will switch to use latest release and support Java 16.

**Comment by LorenzoBettini** [comment] 2021-05-21 12:52
OK, right! indeed for Eclipse 4.19 there's an additional patch for Java 16.
Thanks for the clarification.
If you think it's worthwhile to keep this issue open, otherwise please close it.

**Comment by akurtakov** [comment] 2021-05-21 12:56
It doesn't hurt keeping it open.

**Comment by mhdstg** [comment] 2021-07-05 09:45
Is it already foreseeable when the next Tycho version support for Java 16 will be available?

**Comment by mickaelistria** [comment] 2021-07-05 09:57
It might support it now since Tycho uses newer ECJ. Please try Tycho 2.4.0-SNAPSHOT as described in https://github.com/eclipse/tycho/blob/master/CONTRIBUTING.md#try-snapshots-and-report-issues and report whether this is working or not.

**Comment by mhdstg** [comment] 2021-07-06 06:40
Thanks for your quick reaction. I can confirm that this snapshot works with JDK 16.

**Comment by mickaelistria** [comment] 2021-07-06 07:07
Thanks for testing @mhdstg !

**Closed by mickaelistria** 2021-07-06 07:07 UTC
Labels: enhancement
